"""
field_entry.py — GroundSense Field Entry App

A lightweight Streamlit form for recording field samples. Each sample's
SampleID is auto-generated by joining structured fields with underscores:

    SampleID = SiteID_TimeOfDay_Position_Protocol_Location_Initials

Layout
------
Two columns, side-by-side:
  • LEFT  — input fields (SiteID, Time of Day, Position, Protocol,
            Location, Initials, Replicates)
  • RIGHT — live SampleID preview + Review table of all rows

After a successful "Add Sample", all input fields and toggles reset to
their defaults so the next sample can be entered immediately.

Output
------
Writes `<repo>/data/site_databases/XRF_Site_Analysis_Database.csv` —
columns: SiteID, SampleID. This is the format the dashboard reads.
"""

import csv
import os
from datetime import datetime

import pandas as pd
import streamlit as st


# ═══════════════════════════════════════════════
#  CONSTANTS
# ═══════════════════════════════════════════════
COLUMNS = ["SiteID", "SampleID"]
OUTPUT_FILENAME = "XRF_Site_Analysis_Database.csv"

TIME_OPTIONS = ["AM", "PM", "Other"]
POSITION_OPTIONS = ["Front", "Back", "Side", "Other"]
PROTOCOL_OPTIONS = ["HUD", "PIIT", "MIELKE", "Other"]

# Widget keys — kept in one place so the reset helper can target them precisely.
WIDGET_KEYS = [
    "site_id_input",
    "time_choice", "time_other",
    "position_choice", "position_other",
    "protocol_choice", "protocol_other",
    "location_input",
    "initials_input",
    "replicates_input",
]


# ═══════════════════════════════════════════════
#  PATH RESOLUTION
# ═══════════════════════════════════════════════
def get_repo_root() -> str:
    """Return absolute path to the repo root (one level above /src)."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def get_output_path() -> str:
    """Where to write the field CSV — same place the dashboard reads from."""
    return os.path.join(
        get_repo_root(), "data", "site_databases", OUTPUT_FILENAME
    )


# ═══════════════════════════════════════════════
#  EXISTING-DATA LOADER / WRITER
# ═══════════════════════════════════════════════
def load_existing_rows(path: str) -> pd.DataFrame:
    """Load existing field CSV so users can append rather than overwrite."""
    if not os.path.exists(path):
        return pd.DataFrame(columns=COLUMNS)
    try:
        df = pd.read_csv(path, dtype=str).fillna("")
        for c in COLUMNS:
            if c not in df.columns:
                df[c] = ""
        return df[COLUMNS]
    except Exception as e:
        st.warning(f"Could not parse existing CSV ({e}). Starting fresh.")
        return pd.DataFrame(columns=COLUMNS)


def write_field_csv(df: pd.DataFrame, path: str) -> None:
    """Write df to disk as a plain single-header CSV with SiteID + SampleID."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    out = df.reindex(columns=COLUMNS).fillna("")
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(COLUMNS)
        for _, row in out.iterrows():
            writer.writerow([row.get(c, "") for c in COLUMNS])


# ═══════════════════════════════════════════════
#  SAMPLE ID BUILDER
# ═══════════════════════════════════════════════
def normalize_site_id(raw: str) -> str:
    """Zero-pad SiteID if it looks like a date.

    The convention is sampling date in ISO form (YYYY-MM-DD). Technicians
    sometimes type non-padded dates like '2025-6-24'; we silently canonicalize
    to '2025-06-24' so downstream lookups against site_configs.json (which
    stores the padded form) succeed.

    Non-date SiteIDs (e.g. legacy 'PITT_24June2025') are returned unchanged.
    """
    s = (raw or "").strip()
    if not s:
        return s
    parts = s.split("-")
    if len(parts) == 3 and all(p.isdigit() for p in parts):
        y, m, d = parts
        if len(y) == 4 and 1 <= int(m) <= 12 and 1 <= int(d) <= 31:
            try:
                # Validate it's a real calendar date (catches Feb 30 etc.)
                datetime(int(y), int(m), int(d))
                return f"{int(y):04d}-{int(m):02d}-{int(d):02d}"
            except ValueError:
                return s
    return s


def build_sample_id(
    site_id: str,
    time_of_day: str,
    position: str,
    protocol: str,
    location: str,
    initials: str,
) -> str:
    """Join the six fields with underscores to form the SampleID.

    All fields are stripped. Internal spaces in custom 'Other' values are
    preserved as-is. Caller is responsible for validating non-empty inputs.
    SiteID is normalized via normalize_site_id() so date-like SiteIDs get
    zero-padded consistently.
    """
    parts = [normalize_site_id(site_id), time_of_day, position, protocol, location, initials]
    return "_".join(p.strip() for p in parts)


# ═══════════════════════════════════════════════
#  PAGE
# ═══════════════════════════════════════════════
st.set_page_config(
    page_title="Urban Soil Co-Lab Field Entry",
    page_icon="🌱",
    layout="wide",
)

st.title("🌱 Field Sample Entry")
st.caption(
    "Record SiteID and SampleIDs from the field."
    
)

OUTPUT_PATH = get_output_path()


# ─── Session state init ───
if "rows" not in st.session_state:
    st.session_state.rows = load_existing_rows(OUTPUT_PATH)

# Flag set by the "Add Sample" handler; consumed at the top of the next
# rerun to wipe widget state. We can't mutate widget keys after they've
# been instantiated in the same run, so we do it on the *next* run.
if st.session_state.get("_pending_reset"):
    for k in WIDGET_KEYS:
        if k in st.session_state:
            del st.session_state[k]
    st.session_state["_pending_reset"] = False


# ═══════════════════════════════════════════════
#  TWO-COLUMN LAYOUT — inputs left, preview right
# ═══════════════════════════════════════════════
left_col, right_col = st.columns([1, 1], gap="large")


# ───────────────────────────────────────────────
#  LEFT — INPUTS
# ───────────────────────────────────────────────
with left_col:
    st.subheader("Sample Entry")

    # ── SiteID ──
    site_id = st.text_input(
        "SiteID",
        help="Free-form. Convention: sampling date as YYYY-M-D, e.g. 2025-10-18.",
        key="site_id_input",
    ).strip()

    # ── Time of Day ──
    time_choice = st.radio(
        "Time of Day",
        TIME_OPTIONS,
        horizontal=True,
        key="time_choice",
    )
    if time_choice == "Other":
        time_value = st.text_input(
            "Specify time of day",
            placeholder="e.g. Dawn, Dusk",
            key="time_other",
        ).strip()
    else:
        time_value = time_choice

    # ── Position ──
    position_choice = st.radio(
        "Position",
        POSITION_OPTIONS,
        horizontal=True,
        key="position_choice",
    )
    if position_choice == "Other":
        position_value = st.text_input(
            "Specify position",
            placeholder="e.g. Driveway, Garden",
            key="position_other",
        ).strip()
    else:
        position_value = position_choice

    # ── Protocol ──
    protocol_choice = st.radio(
        "Protocol",
        PROTOCOL_OPTIONS,
        horizontal=True,
        key="protocol_choice",
    )
    if protocol_choice == "Other":
        protocol_value = st.text_input(
            "Specify protocol",
            placeholder="e.g. Custom",
            key="protocol_other",
        ).strip()
    else:
        protocol_value = protocol_choice

    # ── Location (grid) ──
    location_value = st.text_input(
        "Location (grid)",
        placeholder="e.g. A1, A2, B1, B2",
        help="The grid cell within the site, e.g. A1 or B3.",
        key="location_input",
    ).strip()

    # ── Field crew initials ──
    initials_value = st.text_input(
        "Field Crew Initials",
        placeholder="e.g. JD",
        key="initials_input",
    ).strip()

    # ── Replicates ──
    replicates = st.number_input(
        "Number of replicates (rows to write for this SampleID)",
        min_value=1, max_value=10, value=3,
        help="Convention: 3 readings per sample, so 3 rows per SampleID.",
        key="replicates_input",
    )

    # ── Add button ──
    add_clicked = st.button(
        "➕ Add Sample", type="primary", use_container_width=True,
    )

    if add_clicked:
        missing = []
        if not site_id:        missing.append("SiteID")
        if not time_value:     missing.append("Time of Day")
        if not position_value: missing.append("Position")
        if not protocol_value: missing.append("Protocol")
        if not location_value: missing.append("Location")
        if not initials_value: missing.append("Initials")

        if missing:
            st.warning(f"Missing required fields: {', '.join(missing)}.")
        else:
            sample_id = build_sample_id(
                site_id, time_value, position_value,
                protocol_value, location_value, initials_value,
            )
            normalized_site_id = normalize_site_id(site_id)
            additions = [
                {"SiteID": normalized_site_id, "SampleID": sample_id}
                for _ in range(int(replicates))
            ]
            st.session_state.rows = pd.concat(
                [st.session_state.rows, pd.DataFrame(additions, columns=COLUMNS)],
                ignore_index=True,
            )
            # Stash a one-shot success message + trigger reset on next rerun.
            st.session_state["_last_added"] = (sample_id, int(replicates))
            st.session_state["_pending_reset"] = True
            st.rerun()


# ───────────────────────────────────────────────
#  RIGHT — PREVIEW + REVIEW
# ───────────────────────────────────────────────
with right_col:
    st.subheader("Preview")

    # One-shot success message after a successful add (survives the reset rerun).
    last_added = st.session_state.pop("_last_added", None)
    if last_added:
        sid, n = last_added
        st.success(f"Added {n} row(s):\n`{sid}`")

    # Live preview of the SampleID being built.
    all_filled = all([
        site_id, time_value, position_value,
        protocol_value, location_value, initials_value,
    ])
    if all_filled:
        preview = build_sample_id(
            site_id, time_value, position_value,
            protocol_value, location_value, initials_value,
        )
        st.info(f"**SampleID preview:**\n\n`{preview}`")
    else:
        st.caption("Fill all fields on the left to see a SampleID preview.")

    st.markdown("---")
    st.subheader("Review")

    current = st.session_state.rows

    m1, m2, m3 = st.columns(3)
    m1.metric("Total rows", len(current))
    m2.metric(
        "Unique SampleIDs",
        int(current["SampleID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
    )
    m3.metric(
        "Unique SiteIDs",
        int(current["SiteID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
    )

    if len(current):
        edited = st.data_editor(
            current[COLUMNS],
            num_rows="dynamic",
            use_container_width=True,
            hide_index=True,
            key="editor",
        )
        st.session_state.rows = edited.reindex(columns=COLUMNS).fillna("")
    else:
        st.info("No rows yet. Add some on the left.")


# ═══════════════════════════════════════════════
#  SAVE BAR (full-width below)
# ═══════════════════════════════════════════════
st.markdown("---")
st.subheader("Save")

col_save, col_clear, col_reload = st.columns(3)

with col_save:
    if st.button("💾 Save to disk", type="primary", use_container_width=True):
        try:
            write_field_csv(st.session_state.rows, OUTPUT_PATH)
            st.success(f"Saved {len(st.session_state.rows)} rows.")
        except Exception as e:
            st.error(f"Save failed: {e}")

with col_clear:
    if st.button("🗑️ Clear all (in-memory)", use_container_width=True):
        st.session_state.rows = pd.DataFrame(columns=COLUMNS)
        st.rerun()

with col_reload:
    if st.button("↻ Reload from disk", use_container_width=True):
        st.session_state.rows = load_existing_rows(OUTPUT_PATH)
        st.rerun()


# with st.expander("ℹ️ Where does the resident address come from then?"):
#     st.markdown(
#         """
# The dashboard reads resident PII from a **local-only** file path,
# configured via the `SOIL_COLAB_PII_PATH` environment variable, with a
# default of `~/.soil_colab/residents_private.csv`.

# That file should have these columns (single header row):

# ```
# SiteID,Address,City,ZipCode,FirstName,LastName
# 2025-6-24,179 Cleveland Ave,Buffalo,14222,Lacey,Carpenter
# 2025-7-8,102 Putnam St,Buffalo,14213,Alexandra,Judelsohn
# ...
# ```

# The dashboard joins on `SiteID`. If the file doesn't exist, it falls
# back to "Unknown Address" — nothing breaks. Keep that file outside the repo.
#         """
#     )