# # """
# # field_entry.py — GroundSense Field Entry App

# # A lightweight Streamlit form for recording field samples. Each sample's
# # SampleID is auto-generated by joining structured fields with underscores:

# #     SampleID = SiteID_TimeOfDay_Position_Protocol_Location_Initials

# # Layout
# # ------
# # Two columns, side-by-side:
# #   • LEFT  — input fields (SiteID, Time of Day, Position, Protocol,
# #             Location, Initials, Replicates)
# #   • RIGHT — live SampleID preview + Review table of all rows

# # After a successful "Add Sample", all input fields and toggles reset to
# # their defaults so the next sample can be entered immediately.

# # Output
# # ------
# # Writes `<repo>/data/site_databases/SiteID_SampleID.csv` —
# # columns: SiteID, SampleID. This is the format the dashboard reads.
# # """

# # import csv
# # import os
# # from datetime import datetime

# # import pandas as pd
# # import streamlit as st


# # # ═══════════════════════════════════════════════
# # #  CONSTANTS
# # # ═══════════════════════════════════════════════
# # COLUMNS = ["SiteID", "SampleID"]
# # OUTPUT_FILENAME = "SiteID_SampleID.csv"

# # TIME_OPTIONS = ["AM", "PM", "Other"]
# # POSITION_OPTIONS = ["Front", "Back", "Side", "Other"]
# # PROTOCOL_OPTIONS = ["HUD", "PIIT", "MIELKE", "Other"]

# # # Widget keys — kept in one place so the reset helper can target them precisely.
# # WIDGET_KEYS = [
# #     "site_id_input",
# #     "time_choice", "time_other",
# #     "position_choice", "position_other",
# #     "protocol_choice", "protocol_other",
# #     "location_input",
# #     "initials_input",
# #     "replicates_input",
# # ]


# # # ═══════════════════════════════════════════════
# # #  PATH RESOLUTION
# # # ═══════════════════════════════════════════════
# # def get_repo_root() -> str:
# #     """Return absolute path to the repo root (one level above /src)."""
# #     return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


# # def get_output_path() -> str:
# #     """Where to write the field CSV — same place the dashboard reads from."""
# #     return os.path.join(
# #         get_repo_root(), "data", "site_databases", OUTPUT_FILENAME
# #     )


# # # ═══════════════════════════════════════════════
# # #  EXISTING-DATA LOADER / WRITER
# # # ═══════════════════════════════════════════════
# # def load_existing_rows(path: str) -> pd.DataFrame:
# #     """Load existing field CSV so users can append rather than overwrite."""
# #     if not os.path.exists(path):
# #         return pd.DataFrame(columns=COLUMNS)
# #     try:
# #         df = pd.read_csv(path, dtype=str).fillna("")
# #         for c in COLUMNS:
# #             if c not in df.columns:
# #                 df[c] = ""
# #         return df[COLUMNS]
# #     except Exception as e:
# #         st.warning(f"Could not parse existing CSV ({e}). Starting fresh.")
# #         return pd.DataFrame(columns=COLUMNS)


# # # REPLACEMENT for write_field_csv in field_entry.py (lines 88-96)

# # def write_field_csv(df: pd.DataFrame, path: str) -> None:
# #     """Append session rows to the on-disk CSV without clobbering existing rows.

# #     Re-reads disk right before writing, compares against the session
# #     DataFrame on (SiteID, SampleID) tuples with replicate-count awareness,
# #     and appends only the delta. This protects:
# #       • Manually-prepended historical rows (your backfill case)
# #       • Rows written by other Streamlit sessions while this one was open
# #       • The replicate convention (3 identical rows per SampleID stay 3)

# #     Writes atomically (tempfile + os.replace) so a crash or SharePoint
# #     sync lock mid-write can't corrupt the file.
# #     """
# #     import tempfile, time
# #     os.makedirs(os.path.dirname(path), exist_ok=True)
# #     session_rows = df.reindex(columns=COLUMNS).fillna("")

# #     last_err = None
# #     for attempt in range(5):
# #         try:
# #             on_disk = load_existing_rows(path)

# #             # Replicate-aware delta: how many of each (SiteID, SampleID)
# #             # pair does the session have that disk doesn't?
# #             disk_counts = (
# #                 on_disk.groupby(COLUMNS).size()
# #                 if len(on_disk) else pd.Series(dtype=int)
# #             )
# #             sess_counts = (
# #                 session_rows.groupby(COLUMNS).size()
# #                 if len(session_rows) else pd.Series(dtype=int)
# #             )

# #             to_append = []
# #             for key, n_sess in sess_counts.items():
# #                 n_disk = int(disk_counts.get(key, 0))
# #                 delta = int(n_sess) - n_disk
# #                 if delta > 0:
# #                     site_id, sample_id = key
# #                     to_append.extend(
# #                         [{"SiteID": site_id, "SampleID": sample_id}] * delta
# #                     )

# #             if not to_append:
# #                 return  # Nothing new; leave disk untouched.

# #             combined = pd.concat(
# #                 [on_disk, pd.DataFrame(to_append, columns=COLUMNS)],
# #                 ignore_index=True,
# #             ).reindex(columns=COLUMNS).fillna("")

# #             # Atomic write
# #             dir_ = os.path.dirname(path)
# #             fd, tmp_path = tempfile.mkstemp(prefix=".tmp_", suffix=".csv", dir=dir_)
# #             try:
# #                 with os.fdopen(fd, "w", newline="", encoding="utf-8") as f:
# #                     writer = csv.writer(f)
# #                     writer.writerow(COLUMNS)
# #                     for _, row in combined.iterrows():
# #                         writer.writerow([row.get(c, "") for c in COLUMNS])
# #                 os.replace(tmp_path, path)
# #             except Exception:
# #                 if os.path.exists(tmp_path):
# #                     try: os.remove(tmp_path)
# #                     except OSError: pass
# #                 raise
# #             return

# #         except PermissionError as e:
# #             last_err = e
# #             time.sleep(0.5 * (2 ** attempt))
# #     raise RuntimeError(
# #         f"Could not write {path} after 5 attempts (likely SharePoint "
# #         f"sync lock). Last error: {last_err}"
# #     )


# # # ═══════════════════════════════════════════════
# # #  SAMPLE ID BUILDER
# # # ═══════════════════════════════════════════════
# # def normalize_site_id(raw: str) -> str:
# #     """Zero-pad SiteID if it looks like a date.

# #     The convention is sampling date in ISO form (YYYY-MM-DD). Technicians
# #     sometimes type non-padded dates like '2025-6-24'; we silently canonicalize
# #     to '2025-06-24' so downstream lookups against site_configs.json (which
# #     stores the padded form) succeed.

# #     Non-date SiteIDs (e.g. legacy 'PITT_24June2025') are returned unchanged.
# #     """
# #     s = (raw or "").strip()
# #     if not s:
# #         return s
# #     parts = s.split("-")
# #     if len(parts) == 3 and all(p.isdigit() for p in parts):
# #         y, m, d = parts
# #         if len(y) == 4 and 1 <= int(m) <= 12 and 1 <= int(d) <= 31:
# #             try:
# #                 # Validate it's a real calendar date (catches Feb 30 etc.)
# #                 datetime(int(y), int(m), int(d))
# #                 return f"{int(y):04d}-{int(m):02d}-{int(d):02d}"
# #             except ValueError:
# #                 return s
# #     return s


# # def build_sample_id(
# #     site_id: str,
# #     time_of_day: str,
# #     position: str,
# #     protocol: str,
# #     location: str,
# #     initials: str,
# # ) -> str:
# #     """Join the six fields with underscores to form the SampleID.

# #     All fields are stripped. Internal spaces in custom 'Other' values are
# #     preserved as-is. Caller is responsible for validating non-empty inputs.
# #     SiteID is normalized via normalize_site_id() so date-like SiteIDs get
# #     zero-padded consistently.
# #     """
# #     parts = [normalize_site_id(site_id), time_of_day, position, protocol, location, initials]
# #     return "_".join(p.strip() for p in parts)


# # # ═══════════════════════════════════════════════
# # #  PAGE
# # # ═══════════════════════════════════════════════
# # st.set_page_config(
# #     page_title="Urban Soil Co-Lab Field Entry",
# #     page_icon="🌱",
# #     layout="wide",
# # )

# # st.title("🌱 Field Sample Entry")
# # st.caption(
# #     "Record SiteID and SampleIDs from the field."
    
# # )

# # OUTPUT_PATH = get_output_path()


# # # ─── Session state init ───
# # if "rows" not in st.session_state:
# #     st.session_state.rows = load_existing_rows(OUTPUT_PATH)

# # # Flag set by the "Add Sample" handler; consumed at the top of the next
# # # rerun to wipe widget state. We can't mutate widget keys after they've
# # # been instantiated in the same run, so we do it on the *next* run.
# # if st.session_state.get("_pending_reset"):
# #     for k in WIDGET_KEYS:
# #         if k in st.session_state:
# #             del st.session_state[k]
# #     st.session_state["_pending_reset"] = False


# # # ═══════════════════════════════════════════════
# # #  TWO-COLUMN LAYOUT — inputs left, preview right
# # # ═══════════════════════════════════════════════
# # left_col, right_col = st.columns([1, 1], gap="large")


# # # ───────────────────────────────────────────────
# # #  LEFT — INPUTS
# # # ───────────────────────────────────────────────
# # with left_col:
# #     st.subheader("Sample Entry")

# #     # ── SiteID ──
# #     site_id = st.text_input(
# #         "SiteID",
# #         help="Free-form. Convention: sampling date as YYYY-M-D, e.g. 2025-10-18.",
# #         key="site_id_input",
# #     ).strip()

# #     # ── Time of Day ──
# #     time_choice = st.radio(
# #         "Time of Day",
# #         TIME_OPTIONS,
# #         horizontal=True,
# #         key="time_choice",
# #     )
# #     if time_choice == "Other":
# #         time_value = st.text_input(
# #             "Specify time of day",
# #             placeholder="e.g. Dawn, Dusk",
# #             key="time_other",
# #         ).strip()
# #     else:
# #         time_value = time_choice

# #     # ── Position ──
# #     position_choice = st.radio(
# #         "Position",
# #         POSITION_OPTIONS,
# #         horizontal=True,
# #         key="position_choice",
# #     )
# #     if position_choice == "Other":
# #         position_value = st.text_input(
# #             "Specify position",
# #             placeholder="e.g. Driveway, Garden",
# #             key="position_other",
# #         ).strip()
# #     else:
# #         position_value = position_choice

# #     # ── Protocol ──
# #     protocol_choice = st.radio(
# #         "Protocol",
# #         PROTOCOL_OPTIONS,
# #         horizontal=True,
# #         key="protocol_choice",
# #     )
# #     if protocol_choice == "Other":
# #         protocol_value = st.text_input(
# #             "Specify protocol",
# #             placeholder="e.g. Custom",
# #             key="protocol_other",
# #         ).strip()
# #     else:
# #         protocol_value = protocol_choice

# #     # ── Location (grid) ──
# #     location_value = st.text_input(
# #         "Location (grid)",
# #         placeholder="e.g. A1, A2, B1, B2",
# #         help="The grid cell within the site, e.g. A1 or B3.",
# #         key="location_input",
# #     ).strip()

# #     # ── Field crew initials ──
# #     initials_value = st.text_input(
# #         "Field Crew Initials",
# #         placeholder="e.g. JD",
# #         key="initials_input",
# #     ).strip()

# #     # ── Replicates ──
# #     replicates = st.number_input(
# #         "Number of replicates (rows to write for this SampleID)",
# #         min_value=1, max_value=10, value=3,
# #         help="Convention: 3 readings per sample, so 3 rows per SampleID.",
# #         key="replicates_input",
# #     )

# #     # ── Add button ──
# #     add_clicked = st.button(
# #         "➕ Add Sample", type="primary", use_container_width=True,
# #     )

# #     if add_clicked:
# #         missing = []
# #         if not site_id:        missing.append("SiteID")
# #         if not time_value:     missing.append("Time of Day")
# #         if not position_value: missing.append("Position")
# #         if not protocol_value: missing.append("Protocol")
# #         if not location_value: missing.append("Location")
# #         if not initials_value: missing.append("Initials")

# #         if missing:
# #             st.warning(f"Missing required fields: {', '.join(missing)}.")
# #         else:
# #             sample_id = build_sample_id(
# #                 site_id, time_value, position_value,
# #                 protocol_value, location_value, initials_value,
# #             )
# #             normalized_site_id = normalize_site_id(site_id)
# #             additions = [
# #                 {"SiteID": normalized_site_id, "SampleID": sample_id}
# #                 for _ in range(int(replicates))
# #             ]
# #             st.session_state.rows = pd.concat(
# #                 [st.session_state.rows, pd.DataFrame(additions, columns=COLUMNS)],
# #                 ignore_index=True,
# #             )
# #             # Stash a one-shot success message + trigger reset on next rerun.
# #             st.session_state["_last_added"] = (sample_id, int(replicates))
# #             st.session_state["_pending_reset"] = True
# #             st.rerun()


# # # ───────────────────────────────────────────────
# # #  RIGHT — PREVIEW + REVIEW
# # # ───────────────────────────────────────────────
# # with right_col:
# #     st.subheader("Preview")

# #     # One-shot success message after a successful add (survives the reset rerun).
# #     last_added = st.session_state.pop("_last_added", None)
# #     if last_added:
# #         sid, n = last_added
# #         st.success(f"Added {n} row(s):\n`{sid}`")

# #     # Live preview of the SampleID being built.
# #     all_filled = all([
# #         site_id, time_value, position_value,
# #         protocol_value, location_value, initials_value,
# #     ])
# #     if all_filled:
# #         preview = build_sample_id(
# #             site_id, time_value, position_value,
# #             protocol_value, location_value, initials_value,
# #         )
# #         st.info(f"**SampleID preview:**\n\n`{preview}`")
# #     else:
# #         st.caption("Fill all fields on the left to see a SampleID preview.")

# #     st.markdown("---")
# #     st.subheader("Review")

# #     current = st.session_state.rows

# #     m1, m2, m3 = st.columns(3)
# #     m1.metric("Total rows", len(current))
# #     m2.metric(
# #         "Unique SampleIDs",
# #         int(current["SampleID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
# #     )
# #     m3.metric(
# #         "Unique SiteIDs",
# #         int(current["SiteID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
# #     )

# #     if len(current):
# #         edited = st.data_editor(
# #             current[COLUMNS],
# #             num_rows="dynamic",
# #             use_container_width=True,
# #             hide_index=True,
# #             key="editor",
# #         )
# #         st.session_state.rows = edited.reindex(columns=COLUMNS).fillna("")
# #     else:
# #         st.info("No rows yet. Add some on the left.")


# # # ═══════════════════════════════════════════════
# # #  SAVE BAR (full-width below)
# # # ═══════════════════════════════════════════════
# # st.markdown("---")
# # st.subheader("Save")

# # col_save, col_clear, col_reload = st.columns(3)

# # with col_save:
# #     if st.button("💾 Save to disk", type="primary", use_container_width=True):
# #         try:
# #             write_field_csv(st.session_state.rows, OUTPUT_PATH)
# #             st.success(f"Saved {len(st.session_state.rows)} rows.")
# #         except Exception as e:
# #             st.error(f"Save failed: {e}")

# # with col_clear:
# #     if st.button("🗑️ Clear all (in-memory)", use_container_width=True):
# #         st.session_state.rows = pd.DataFrame(columns=COLUMNS)
# #         st.rerun()

# # with col_reload:
# #     if st.button("↻ Reload from disk", use_container_width=True):
# #         st.session_state.rows = load_existing_rows(OUTPUT_PATH)
# #         st.rerun()


# # # with st.expander("ℹ️ Where does the resident address come from then?"):
# # #     st.markdown(
# # #         """
# # # The dashboard reads resident PII from a **local-only** file path,
# # # configured via the `SOIL_COLAB_PII_PATH` environment variable, with a
# # # default of `~/.soil_colab/residents_private.csv`.

# # # That file should have these columns (single header row):

# # # ```
# # # SiteID,Address,City,ZipCode,FirstName,LastName
# # # 2025-6-24,179 Cleveland Ave,Buffalo,14222,Lacey,Carpenter
# # # 2025-7-8,102 Putnam St,Buffalo,14213,Alexandra,Judelsohn
# # # ...
# # # ```

# # # The dashboard joins on `SiteID`. If the file doesn't exist, it falls
# # # back to "Unknown Address" — nothing breaks. Keep that file outside the repo.
# # #         """
# # #     )

# """
# field_entry.py — GroundSense Field Entry App

# A lightweight Streamlit form for recording field samples. Each sample's
# SampleID is auto-generated by joining structured fields with underscores.
# The exact format depends on the chosen protocol:

#     HUD     : SiteID_[AM/PM_]HUD_<Drip|Play|Yard>_Initials
#     MIELKE  : SiteID_[AM/PM_]MIELKE_<RoadName|BuildingType|Lawn>_Initials
#     PIIT    : SiteID_[AM/PM_]PIIT_<Location(grid)>_Initials
#     Other   : SiteID_[AM/PM_]<Protocol>_<Position>_<Location>_Initials  (legacy)

# The AM/PM segment is only included when the technician indicates that
# multiple sites are being sampled on the same day. For single-site days,
# Time of Day is omitted from the SampleID entirely.

# Layout
# ------
# Two columns, side-by-side:
#   • LEFT  — input fields (Protocol-driven; SiteID, AM/PM (conditional),
#             protocol-specific descriptor, Initials, Replicates)
#   • RIGHT — live SampleID preview + Review table of all rows

# After a successful "Add Sample", all input fields and toggles reset to
# their defaults so the next sample can be entered immediately.

# Output
# ------
# Writes `<repo>/data/site_databases/SiteID_SampleID.csv` —
# columns: SiteID, SampleID. This is the format the dashboard reads.
# """

# import csv
# import os
# from datetime import datetime

# import pandas as pd
# import streamlit as st


# # ═══════════════════════════════════════════════
# #  CONSTANTS
# # ═══════════════════════════════════════════════
# COLUMNS = ["SiteID", "SampleID"]
# OUTPUT_FILENAME = "SiteID_SampleID.csv"

# TIME_OPTIONS = ["AM", "PM", "Other"]
# POSITION_OPTIONS = ["Front", "Back", "Side", "Other"]
# PROTOCOL_OPTIONS = ["HUD", "PIIT", "MIELKE", "Other"]
# HUD_DESCRIPTOR_OPTIONS = ["Drip", "Play", "Yard", "Other"]

# # Widget keys — kept in one place so the reset helper can target them precisely.
# WIDGET_KEYS = [
#     "site_id_input",
#     "multi_site_toggle",
#     "time_choice", "time_other",
#     "protocol_choice", "protocol_other",
#     "hud_descriptor_choice", "hud_descriptor_other",
#     "mielke_descriptor_input",
#     "piit_location_input",
#     "position_choice", "position_other",
#     "location_input",
#     "initials_input",
#     "replicates_input",
# ]


# # ═══════════════════════════════════════════════
# #  PATH RESOLUTION
# # ═══════════════════════════════════════════════
# def get_repo_root() -> str:
#     """Return absolute path to the repo root (one level above /src)."""
#     return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


# def get_output_path() -> str:
#     """Where to write the field CSV — same place the dashboard reads from."""
#     return os.path.join(
#         get_repo_root(), "data", "site_databases", OUTPUT_FILENAME
#     )


# # ═══════════════════════════════════════════════
# #  EXISTING-DATA LOADER / WRITER
# # ═══════════════════════════════════════════════
# def load_existing_rows(path: str) -> pd.DataFrame:
#     """Load existing field CSV so users can append rather than overwrite."""
#     if not os.path.exists(path):
#         return pd.DataFrame(columns=COLUMNS)
#     try:
#         df = pd.read_csv(path, dtype=str).fillna("")
#         for c in COLUMNS:
#             if c not in df.columns:
#                 df[c] = ""
#         return df[COLUMNS]
#     except Exception as e:
#         st.warning(f"Could not parse existing CSV ({e}). Starting fresh.")
#         return pd.DataFrame(columns=COLUMNS)


# def write_field_csv(df: pd.DataFrame, path: str) -> None:
#     """Append session rows to the on-disk CSV without clobbering existing rows.

#     Re-reads disk right before writing, compares against the session
#     DataFrame on (SiteID, SampleID) tuples with replicate-count awareness,
#     and appends only the delta. This protects:
#       • Manually-prepended historical rows (your backfill case)
#       • Rows written by other Streamlit sessions while this one was open
#       • The replicate convention (3 identical rows per SampleID stay 3)

#     Writes atomically (tempfile + os.replace) so a crash or SharePoint
#     sync lock mid-write can't corrupt the file.
#     """
#     import tempfile, time
#     os.makedirs(os.path.dirname(path), exist_ok=True)
#     session_rows = df.reindex(columns=COLUMNS).fillna("")

#     last_err = None
#     for attempt in range(5):
#         try:
#             on_disk = load_existing_rows(path)

#             # Replicate-aware delta: how many of each (SiteID, SampleID)
#             # pair does the session have that disk doesn't?
#             disk_counts = (
#                 on_disk.groupby(COLUMNS).size()
#                 if len(on_disk) else pd.Series(dtype=int)
#             )
#             sess_counts = (
#                 session_rows.groupby(COLUMNS).size()
#                 if len(session_rows) else pd.Series(dtype=int)
#             )

#             to_append = []
#             for key, n_sess in sess_counts.items():
#                 n_disk = int(disk_counts.get(key, 0))
#                 delta = int(n_sess) - n_disk
#                 if delta > 0:
#                     site_id, sample_id = key
#                     to_append.extend(
#                         [{"SiteID": site_id, "SampleID": sample_id}] * delta
#                     )

#             if not to_append:
#                 return  # Nothing new; leave disk untouched.

#             combined = pd.concat(
#                 [on_disk, pd.DataFrame(to_append, columns=COLUMNS)],
#                 ignore_index=True,
#             ).reindex(columns=COLUMNS).fillna("")

#             # Atomic write
#             dir_ = os.path.dirname(path)
#             fd, tmp_path = tempfile.mkstemp(prefix=".tmp_", suffix=".csv", dir=dir_)
#             try:
#                 with os.fdopen(fd, "w", newline="", encoding="utf-8") as f:
#                     writer = csv.writer(f)
#                     writer.writerow(COLUMNS)
#                     for _, row in combined.iterrows():
#                         writer.writerow([row.get(c, "") for c in COLUMNS])
#                 os.replace(tmp_path, path)
#             except Exception:
#                 if os.path.exists(tmp_path):
#                     try: os.remove(tmp_path)
#                     except OSError: pass
#                 raise
#             return

#         except PermissionError as e:
#             last_err = e
#             time.sleep(0.5 * (2 ** attempt))
#     raise RuntimeError(
#         f"Could not write {path} after 5 attempts (likely SharePoint "
#         f"sync lock). Last error: {last_err}"
#     )


# # ═══════════════════════════════════════════════
# #  SAMPLE ID BUILDER
# # ═══════════════════════════════════════════════
# def normalize_site_id(raw: str) -> str:
#     """Zero-pad SiteID if it looks like a date.

#     The convention is sampling date in ISO form (YYYY-MM-DD). Technicians
#     sometimes type non-padded dates like '2025-6-24'; we silently canonicalize
#     to '2025-06-24' so downstream lookups against site_configs.json (which
#     stores the padded form) succeed.

#     Non-date SiteIDs (e.g. legacy 'PITT_24June2025') are returned unchanged.
#     """
#     s = (raw or "").strip()
#     if not s:
#         return s
#     parts = s.split("-")
#     if len(parts) == 3 and all(p.isdigit() for p in parts):
#         y, m, d = parts
#         if len(y) == 4 and 1 <= int(m) <= 12 and 1 <= int(d) <= 31:
#             try:
#                 # Validate it's a real calendar date (catches Feb 30 etc.)
#                 datetime(int(y), int(m), int(d))
#                 return f"{int(y):04d}-{int(m):02d}-{int(d):02d}"
#             except ValueError:
#                 return s
#     return s


# def _sanitize_segment(s: str) -> str:
#     """Make a free-text field safe to drop into an underscore-joined ID.

#     Strips leading/trailing whitespace and replaces any internal whitespace
#     runs with single underscores so 'Front Yard' becomes 'Front_Yard'.
#     Without this, internal spaces would survive into the SampleID and break
#     parsing assumptions elsewhere in the pipeline.
#     """
#     return "_".join((s or "").strip().split())


# def build_sample_id(
#     site_id: str,
#     time_of_day: str,       # "" means omit (single-site day)
#     protocol: str,
#     descriptor: str,        # protocol-specific middle segment(s); already sanitized
#     initials: str,
# ) -> str:
#     """Join the structured fields with underscores to form the SampleID.

#     Format: SiteID_[TimeOfDay_]Protocol_Descriptor_Initials

#     `time_of_day` is included only when non-empty; this is how the
#     "single site today" case omits AM/PM. `descriptor` is whatever
#     protocol-specific middle segment(s) the caller built (already
#     sanitized and underscore-joined if multi-part). SiteID is normalized
#     via normalize_site_id() so date-like SiteIDs get zero-padded consistently.
#     """
#     parts = [normalize_site_id(site_id)]
#     if time_of_day:
#         parts.append(time_of_day.strip())
#     parts.extend([protocol.strip(), descriptor.strip(), initials.strip()])
#     return "_".join(parts)


# # ═══════════════════════════════════════════════
# #  PAGE
# # ═══════════════════════════════════════════════
# st.set_page_config(
#     page_title="Urban Soil Co-Lab Field Entry",
#     page_icon="🌱",
#     layout="wide",
# )

# st.title("🌱 Field Sample Entry")
# st.caption(
#     "Record SiteID and SampleIDs from the field."
# )

# OUTPUT_PATH = get_output_path()


# # ─── Session state init ───
# if "rows" not in st.session_state:
#     st.session_state.rows = load_existing_rows(OUTPUT_PATH)

# # Flag set by the "Add Sample" handler; consumed at the top of the next
# # rerun to wipe widget state. We can't mutate widget keys after they've
# # been instantiated in the same run, so we do it on the *next* run.
# if st.session_state.get("_pending_reset"):
#     for k in WIDGET_KEYS:
#         if k in st.session_state:
#             del st.session_state[k]
#     st.session_state["_pending_reset"] = False


# # ═══════════════════════════════════════════════
# #  TWO-COLUMN LAYOUT — inputs left, preview right
# # ═══════════════════════════════════════════════
# left_col, right_col = st.columns([1, 1], gap="large")


# # ───────────────────────────────────────────────
# #  LEFT — INPUTS
# # ───────────────────────────────────────────────
# with left_col:
#     st.subheader("Sample Entry")

#     # ── SiteID ──
#     site_id = st.text_input(
#         "SiteID",
#         help="Free-form. Convention: sampling date as YYYY-M-D, e.g. 2025-10-18.",
#         key="site_id_input",
#     ).strip()

#     # ── Multiple sites today? ──
#     # Controls whether AM/PM is included in the SampleID. Default off
#     # (most days are single-site); technician flips it on when they know
#     # they'll be sampling more than one site that day.
#     multi_site_today = st.checkbox(
#         "Multiple sites sampled today (include AM/PM in SampleID)",
#         value=False,
#         key="multi_site_toggle",
#         help=(
#             "Off → SampleID has no AM/PM segment. "
#             "On → AM/PM is required and appears in the SampleID."
#         ),
#     )

#     # ── Time of Day (only when multi-site) ──
#     if multi_site_today:
#         time_choice = st.radio(
#             "Time of Day",
#             TIME_OPTIONS,
#             horizontal=True,
#             key="time_choice",
#         )
#         if time_choice == "Other":
#             time_value = st.text_input(
#                 "Specify time of day",
#                 placeholder="e.g. Dawn, Dusk",
#                 key="time_other",
#             ).strip()
#         else:
#             time_value = time_choice
#     else:
#         time_value = ""  # Omitted from the SampleID for single-site days.

#     # ── Protocol (drives the rest of the form) ──
#     protocol_choice = st.radio(
#         "Protocol",
#         PROTOCOL_OPTIONS,
#         horizontal=True,
#         key="protocol_choice",
#     )
#     if protocol_choice == "Other":
#         protocol_value = st.text_input(
#             "Specify protocol",
#             placeholder="e.g. Custom",
#             key="protocol_other",
#         ).strip()
#     else:
#         protocol_value = protocol_choice

#     # ── Protocol-specific descriptor fields ──
#     # Each branch sets `descriptor_value` (the middle segment that goes
#     # between the protocol name and the initials in the SampleID), plus
#     # a human-readable `descriptor_label` for the "missing fields" warning.
#     descriptor_value = ""
#     descriptor_label = "Descriptor"

#     if protocol_choice == "HUD":
#         # HUD: SiteID_[AM/PM_]HUD_<Drip|Play|Yard>_Initials
#         descriptor_label = "HUD Location"
#         hud_choice = st.radio(
#             "HUD Location",
#             HUD_DESCRIPTOR_OPTIONS,
#             horizontal=True,
#             key="hud_descriptor_choice",
#             help="Drip line, Play area, or Yard. Use 'Other' if none fit.",
#         )
#         if hud_choice == "Other":
#             descriptor_value = _sanitize_segment(
#                 st.text_input(
#                     "Specify HUD location",
#                     placeholder="e.g. Garden",
#                     key="hud_descriptor_other",
#                 )
#             )
#         else:
#             descriptor_value = hud_choice

#     elif protocol_choice == "MIELKE":
#         # MIELKE: SiteID_[AM/PM_]MIELKE_<RoadName|BuildingType|Lawn>_Initials
#         descriptor_label = "Mielke Descriptor"
#         descriptor_value = _sanitize_segment(
#             st.text_input(
#                 "Road Name / Building Type / Lawn",
#                 placeholder="e.g. MainSt, ResidentialHouse, Lawn",
#                 help=(
#                     "Whichever descriptor fits the sample location: a road "
#                     "name, building type, or 'Lawn'. Internal spaces become "
#                     "underscores so the SampleID stays underscore-delimited."
#                 ),
#                 key="mielke_descriptor_input",
#             )
#         )

#     elif protocol_choice == "PIIT":
#         # PIIT: SiteID_[AM/PM_]PIIT_<Location(grid)>_Initials
#         descriptor_label = "Location (grid)"
#         descriptor_value = _sanitize_segment(
#             st.text_input(
#                 "Location (grid)",
#                 placeholder="e.g. A1, A2, B1, B2",
#                 help="The grid cell within the site, e.g. A1 or B3.",
#                 key="piit_location_input",
#             )
#         )

#     else:
#         # Other / custom protocol: keep the legacy Position + Location combo
#         # so existing workflows don't break. Joined with an underscore to
#         # become a single descriptor segment in the SampleID.
#         position_choice = st.radio(
#             "Position",
#             POSITION_OPTIONS,
#             horizontal=True,
#             key="position_choice",
#         )
#         if position_choice == "Other":
#             position_value = st.text_input(
#                 "Specify position",
#                 placeholder="e.g. Driveway, Garden",
#                 key="position_other",
#             ).strip()
#         else:
#             position_value = position_choice

#         location_value = st.text_input(
#             "Location (grid)",
#             placeholder="e.g. A1, A2, B1, B2",
#             help="The grid cell within the site, e.g. A1 or B3.",
#             key="location_input",
#         ).strip()

#         descriptor_label = "Position + Location"
#         if position_value and location_value:
#             descriptor_value = (
#                 f"{_sanitize_segment(position_value)}_"
#                 f"{_sanitize_segment(location_value)}"
#             )
#         else:
#             descriptor_value = ""  # Validation below will surface the gap.

#     # ── Field crew initials ──
#     initials_value = st.text_input(
#         "Field Crew Initials",
#         placeholder="e.g. JD",
#         key="initials_input",
#     ).strip()

#     # ── Replicates ──
#     replicates = st.number_input(
#         "Number of replicates (rows to write for this SampleID)",
#         min_value=1, max_value=10, value=3,
#         help="Convention: 3 readings per sample, so 3 rows per SampleID.",
#         key="replicates_input",
#     )

#     # ── Add button ──
#     add_clicked = st.button(
#         "➕ Add Sample", type="primary", use_container_width=True,
#     )

#     if add_clicked:
#         missing = []
#         if not site_id:                              missing.append("SiteID")
#         if multi_site_today and not time_value:      missing.append("Time of Day")
#         if not protocol_value:                       missing.append("Protocol")
#         if not descriptor_value:                     missing.append(descriptor_label)
#         if not initials_value:                       missing.append("Initials")

#         if missing:
#             st.warning(f"Missing required fields: {', '.join(missing)}.")
#         else:
#             sample_id = build_sample_id(
#                 site_id=site_id,
#                 time_of_day=time_value,
#                 protocol=protocol_value,
#                 descriptor=descriptor_value,
#                 initials=initials_value,
#             )
#             normalized_site_id = normalize_site_id(site_id)
#             additions = [
#                 {"SiteID": normalized_site_id, "SampleID": sample_id}
#                 for _ in range(int(replicates))
#             ]
#             st.session_state.rows = pd.concat(
#                 [st.session_state.rows, pd.DataFrame(additions, columns=COLUMNS)],
#                 ignore_index=True,
#             )
#             # Stash a one-shot success message + trigger reset on next rerun.
#             st.session_state["_last_added"] = (sample_id, int(replicates))
#             st.session_state["_pending_reset"] = True
#             st.rerun()


# # ───────────────────────────────────────────────
# #  RIGHT — PREVIEW + REVIEW
# # ───────────────────────────────────────────────
# with right_col:
#     st.subheader("Preview")

#     # One-shot success message after a successful add (survives the reset rerun).
#     last_added = st.session_state.pop("_last_added", None)
#     if last_added:
#         sid, n = last_added
#         st.success(f"Added {n} row(s):\n`{sid}`")

#     # Live preview of the SampleID being built.
#     # Time of Day is only required for the preview when multi-site is on.
#     time_ok = (not multi_site_today) or bool(time_value)
#     all_filled = all([
#         site_id, time_ok, protocol_value, descriptor_value, initials_value,
#     ])
#     if all_filled:
#         preview = build_sample_id(
#             site_id=site_id,
#             time_of_day=time_value,
#             protocol=protocol_value,
#             descriptor=descriptor_value,
#             initials=initials_value,
#         )
#         st.info(f"**SampleID preview:**\n\n`{preview}`")
#     else:
#         st.caption("Fill all fields on the left to see a SampleID preview.")

#     st.markdown("---")
#     st.subheader("Review")

#     current = st.session_state.rows

#     m1, m2, m3 = st.columns(3)
#     m1.metric("Total rows", len(current))
#     m2.metric(
#         "Unique SampleIDs",
#         int(current["SampleID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
#     )
#     m3.metric(
#         "Unique SiteIDs",
#         int(current["SiteID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
#     )

#     if len(current):
#         edited = st.data_editor(
#             current[COLUMNS],
#             num_rows="dynamic",
#             use_container_width=True,
#             hide_index=True,
#             key="editor",
#         )
#         st.session_state.rows = edited.reindex(columns=COLUMNS).fillna("")
#     else:
#         st.info("No rows yet. Add some on the left.")


# # ═══════════════════════════════════════════════
# #  SAVE BAR (full-width below)
# # ═══════════════════════════════════════════════
# st.markdown("---")
# st.subheader("Save")

# col_save, col_clear, col_reload = st.columns(3)

# with col_save:
#     if st.button("💾 Save to disk", type="primary", use_container_width=True):
#         try:
#             write_field_csv(st.session_state.rows, OUTPUT_PATH)
#             st.success(f"Saved {len(st.session_state.rows)} rows.")
#         except Exception as e:
#             st.error(f"Save failed: {e}")

# with col_clear:
#     if st.button("🗑️ Clear all (in-memory)", use_container_width=True):
#         st.session_state.rows = pd.DataFrame(columns=COLUMNS)
#         st.rerun()

# with col_reload:
#     if st.button("↻ Reload from disk", use_container_width=True):
#         st.session_state.rows = load_existing_rows(OUTPUT_PATH)
#         st.rerun()

"""
field_entry.py — GroundSense Field Entry App

A lightweight Streamlit form for recording field samples. Each sample's
SampleID is auto-generated by joining structured fields with underscores.
The exact format depends on the chosen protocol:

    HUD     : SiteID_[AM/PM_]HUD_<Drip|Play|Yard>[Index]_Initials
    MIELKE  : SiteID_[AM/PM_]MIELKE_<RoadName|BuildingType|Lawn>_Initials
    PIIT    : SiteID_[AM/PM_]PIIT_<Location(grid)>_Initials
    Other   : SiteID_[AM/PM_]<Protocol>_<Position>_<Location>_Initials  (legacy)

The AM/PM segment is only included when the technician indicates that
multiple sites are being sampled on the same day. For single-site days,
Time of Day is omitted from the SampleID entirely.

Layout
------
Two columns, side-by-side:
  • LEFT  — input fields (Protocol-driven; SiteID, AM/PM (conditional),
            protocol-specific descriptor, Initials, Replicates)
  • RIGHT — live SampleID preview + Review table of all rows

After a successful "Add Sample", all input fields and toggles reset to
their defaults so the next sample can be entered immediately.

Output
------
Writes `<repo>/data/site_databases/SiteID_SampleID.csv` —
columns: SiteID, SampleID. This is the format the dashboard reads.
"""

import csv
import os
from datetime import datetime

import pandas as pd
import streamlit as st


# ═══════════════════════════════════════════════
#  CONSTANTS
# ═══════════════════════════════════════════════
COLUMNS = ["SiteID", "SampleID"]
OUTPUT_FILENAME = "SiteID_SampleID.csv"

TIME_OPTIONS = ["AM", "PM", "Other"]
POSITION_OPTIONS = ["Front", "Back", "Side", "Other"]
PROTOCOL_OPTIONS = ["HUD", "PIIT", "MIELKE", "Other"]
HUD_DESCRIPTOR_OPTIONS = ["Drip", "Play", "Yard", "Other"]

# Widget keys — kept in one place so the reset helper can target them precisely.
WIDGET_KEYS = [
    "site_id_input",
    "multi_site_toggle",
    "time_choice", "time_other",
    "protocol_choice", "protocol_other",
    "hud_descriptor_choice", "hud_descriptor_other", "hud_index_input",
    "mielke_descriptor_input",
    "piit_location_input",
    "position_choice", "position_other",
    "location_input",
    "initials_input",
    "replicates_input",
]


# ═══════════════════════════════════════════════
#  PATH RESOLUTION
# ═══════════════════════════════════════════════
def get_repo_root() -> str:
    """Return absolute path to the repo root (one level above /src)."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def get_output_path() -> str:
    """Where to write the field CSV — same place the dashboard reads from."""
    return os.path.join(
        get_repo_root(), "data", "site_databases", OUTPUT_FILENAME
    )


# ═══════════════════════════════════════════════
#  EXISTING-DATA LOADER / WRITER
# ═══════════════════════════════════════════════
def load_existing_rows(path: str) -> pd.DataFrame:
    """Load existing field CSV so users can append rather than overwrite."""
    if not os.path.exists(path):
        return pd.DataFrame(columns=COLUMNS)
    try:
        df = pd.read_csv(path, dtype=str).fillna("")
        for c in COLUMNS:
            if c not in df.columns:
                df[c] = ""
        return df[COLUMNS]
    except Exception as e:
        st.warning(f"Could not parse existing CSV ({e}). Starting fresh.")
        return pd.DataFrame(columns=COLUMNS)


def write_field_csv(df: pd.DataFrame, path: str) -> None:
    """Append session rows to the on-disk CSV without clobbering existing rows.

    Re-reads disk right before writing, compares against the session
    DataFrame on (SiteID, SampleID) tuples with replicate-count awareness,
    and appends only the delta. This protects:
      • Manually-prepended historical rows (your backfill case)
      • Rows written by other Streamlit sessions while this one was open
      • The replicate convention (3 identical rows per SampleID stay 3)

    Writes atomically (tempfile + os.replace) so a crash or SharePoint
    sync lock mid-write can't corrupt the file.
    """
    import tempfile, time
    os.makedirs(os.path.dirname(path), exist_ok=True)
    session_rows = df.reindex(columns=COLUMNS).fillna("")

    last_err = None
    for attempt in range(5):
        try:
            on_disk = load_existing_rows(path)

            # Replicate-aware delta: how many of each (SiteID, SampleID)
            # pair does the session have that disk doesn't?
            disk_counts = (
                on_disk.groupby(COLUMNS).size()
                if len(on_disk) else pd.Series(dtype=int)
            )
            sess_counts = (
                session_rows.groupby(COLUMNS).size()
                if len(session_rows) else pd.Series(dtype=int)
            )

            to_append = []
            for key, n_sess in sess_counts.items():
                n_disk = int(disk_counts.get(key, 0))
                delta = int(n_sess) - n_disk
                if delta > 0:
                    site_id, sample_id = key
                    to_append.extend(
                        [{"SiteID": site_id, "SampleID": sample_id}] * delta
                    )

            if not to_append:
                return  # Nothing new; leave disk untouched.

            combined = pd.concat(
                [on_disk, pd.DataFrame(to_append, columns=COLUMNS)],
                ignore_index=True,
            ).reindex(columns=COLUMNS).fillna("")

            # Atomic write
            dir_ = os.path.dirname(path)
            fd, tmp_path = tempfile.mkstemp(prefix=".tmp_", suffix=".csv", dir=dir_)
            try:
                with os.fdopen(fd, "w", newline="", encoding="utf-8") as f:
                    writer = csv.writer(f)
                    writer.writerow(COLUMNS)
                    for _, row in combined.iterrows():
                        writer.writerow([row.get(c, "") for c in COLUMNS])
                os.replace(tmp_path, path)
            except Exception:
                if os.path.exists(tmp_path):
                    try: os.remove(tmp_path)
                    except OSError: pass
                raise
            return

        except PermissionError as e:
            last_err = e
            time.sleep(0.5 * (2 ** attempt))
    raise RuntimeError(
        f"Could not write {path} after 5 attempts (likely SharePoint "
        f"sync lock). Last error: {last_err}"
    )


# ═══════════════════════════════════════════════
#  SAMPLE ID BUILDER
# ═══════════════════════════════════════════════
def normalize_site_id(raw: str) -> str:
    """Zero-pad SiteID if it looks like a date.

    The convention is sampling date in ISO form (YYYY-MM-DD). Technicians
    sometimes type non-padded dates like '2025-6-24'; we silently canonicalize
    to '2025-06-24' so downstream lookups against site_configs.json (which
    stores the padded form) succeed.

    Non-date SiteIDs (e.g. legacy 'PITT_24June2025') are returned unchanged.
    """
    s = (raw or "").strip()
    if not s:
        return s
    parts = s.split("-")
    if len(parts) == 3 and all(p.isdigit() for p in parts):
        y, m, d = parts
        if len(y) == 4 and 1 <= int(m) <= 12 and 1 <= int(d) <= 31:
            try:
                # Validate it's a real calendar date (catches Feb 30 etc.)
                datetime(int(y), int(m), int(d))
                return f"{int(y):04d}-{int(m):02d}-{int(d):02d}"
            except ValueError:
                return s
    return s


def _sanitize_segment(s: str) -> str:
    """Make a free-text field safe to drop into an underscore-joined ID.

    Strips leading/trailing whitespace and replaces any internal whitespace
    runs with single underscores so 'Front Yard' becomes 'Front_Yard'.
    Without this, internal spaces would survive into the SampleID and break
    parsing assumptions elsewhere in the pipeline.
    """
    return "_".join((s or "").strip().split())


def build_sample_id(
    site_id: str,
    time_of_day: str,       # "" means omit (single-site day)
    protocol: str,
    descriptor: str,        # protocol-specific middle segment(s); already sanitized
    initials: str,
) -> str:
    """Join the structured fields with underscores to form the SampleID.

    Format: SiteID_[TimeOfDay_]Protocol_Descriptor_Initials

    `time_of_day` is included only when non-empty; this is how the
    "single site today" case omits AM/PM. `descriptor` is whatever
    protocol-specific middle segment(s) the caller built (already
    sanitized and underscore-joined if multi-part). SiteID is normalized
    via normalize_site_id() so date-like SiteIDs get zero-padded consistently.
    """
    parts = [normalize_site_id(site_id)]
    if time_of_day:
        parts.append(time_of_day.strip())
    parts.extend([protocol.strip(), descriptor.strip(), initials.strip()])
    return "_".join(parts)


# ═══════════════════════════════════════════════
#  PAGE
# ═══════════════════════════════════════════════
st.set_page_config(
    page_title="Urban Soil Co-Lab Field Entry",
    page_icon="🌱",
    layout="wide",
)

st.title("🌱 Field Sample Entry")
st.caption(
    "Record SiteID and SampleIDs from the field."
)

OUTPUT_PATH = get_output_path()


# ─── Session state init ───
if "rows" not in st.session_state:
    st.session_state.rows = load_existing_rows(OUTPUT_PATH)

# Flag set by the "Add Sample" handler; consumed at the top of the next
# rerun to wipe widget state. We can't mutate widget keys after they've
# been instantiated in the same run, so we do it on the *next* run.
if st.session_state.get("_pending_reset"):
    for k in WIDGET_KEYS:
        if k in st.session_state:
            del st.session_state[k]
    st.session_state["_pending_reset"] = False


# ═══════════════════════════════════════════════
#  TWO-COLUMN LAYOUT — inputs left, preview right
# ═══════════════════════════════════════════════
left_col, right_col = st.columns([1, 1], gap="large")


# ───────────────────────────────────────────────
#  LEFT — INPUTS
# ───────────────────────────────────────────────
with left_col:
    st.subheader("Sample Entry")

    # ── SiteID ──
    site_id = st.text_input(
        "SiteID",
        help="Free-form. Convention: sampling date as YYYY-M-D, e.g. 2025-10-18.",
        key="site_id_input",
    ).strip()

    # ── Multiple sites today? ──
    # Controls whether AM/PM is included in the SampleID. Default off
    # (most days are single-site); technician flips it on when they know
    # they'll be sampling more than one site that day.
    multi_site_today = st.checkbox(
        "Multiple sites sampled today (include AM/PM in SampleID)",
        value=False,
        key="multi_site_toggle",
        help=(
            "Off → SampleID has no AM/PM segment. "
            "On → AM/PM is required and appears in the SampleID."
        ),
    )

    # ── Time of Day (only when multi-site) ──
    if multi_site_today:
        time_choice = st.radio(
            "Time of Day",
            TIME_OPTIONS,
            horizontal=True,
            key="time_choice",
        )
        if time_choice == "Other":
            time_value = st.text_input(
                "Specify time of day",
                placeholder="e.g. Dawn, Dusk",
                key="time_other",
            ).strip()
        else:
            time_value = time_choice
    else:
        time_value = ""  # Omitted from the SampleID for single-site days.

    # ── Protocol (drives the rest of the form) ──
    protocol_choice = st.radio(
        "Protocol",
        PROTOCOL_OPTIONS,
        horizontal=True,
        key="protocol_choice",
    )
    if protocol_choice == "Other":
        protocol_value = st.text_input(
            "Specify protocol",
            placeholder="e.g. Custom",
            key="protocol_other",
        ).strip()
    else:
        protocol_value = protocol_choice

    # ── Protocol-specific descriptor fields ──
    # Each branch sets `descriptor_value` (the middle segment that goes
    # between the protocol name and the initials in the SampleID), plus
    # a human-readable `descriptor_label` for the "missing fields" warning.
    descriptor_value = ""
    descriptor_label = "Descriptor"

    if protocol_choice == "HUD":
        # HUD: SiteID_[AM/PM_]HUD_<Drip|Play|Yard>[Index]_Initials
        # When a site has multiple instances of the same descriptor (e.g.
        # three drip lines, two yards), the technician picks a non-zero
        # index and it gets concatenated directly onto the descriptor:
        # Drip + 1 → "Drip1", Yard + 2 → "Yard2". Index 0 is the "no number"
        # default — descriptor stays bare.
        descriptor_label = "HUD Location"
        hud_choice = st.radio(
            "HUD Location",
            HUD_DESCRIPTOR_OPTIONS,
            horizontal=True,
            key="hud_descriptor_choice",
            help="Drip line, Play area, or Yard. Use 'Other' if none fit.",
        )
        if hud_choice == "Other":
            hud_base = _sanitize_segment(
                st.text_input(
                    "Specify HUD location",
                    placeholder="e.g. Garden",
                    key="hud_descriptor_other",
                )
            )
        else:
            hud_base = hud_choice

        # Optional numeric index. number_input is the right widget here:
        # it has compact + / – step buttons on the right edge of the box
        # itself (same look as "Number of replicates" below), and it
        # accepts typed values for indexes beyond what stepping would
        # reach. 0 means "no number appended" — we display the help text
        # to that effect rather than trying to relabel 0 as "None" inside
        # the number widget.
        hud_index = st.number_input(
            "Index (0 = no number)",
            min_value=0, max_value=99, value=0, step=1,
            help=(
                "Use when a site has multiple of the same HUD location, "
                "e.g. Drip1, Drip2, Drip3 or Yard1, Yard2. Use the + / – "
                "buttons or type a value. Leave at 0 when there's only "
                "one and no number is needed."
            ),
            key="hud_index_input",
        )

        if hud_base and int(hud_index) > 0:
            descriptor_value = f"{hud_base}{int(hud_index)}"
        else:
            descriptor_value = hud_base

    elif protocol_choice == "MIELKE":
        # MIELKE: SiteID_[AM/PM_]MIELKE_<RoadName|BuildingType|Lawn>_Initials
        descriptor_label = "Mielke Descriptor"
        descriptor_value = _sanitize_segment(
            st.text_input(
                "Road Name / Building Type / Lawn",
                placeholder="e.g. MainSt, ResidentialHouse, Lawn",
                help=(
                    "Whichever descriptor fits the sample location: a road "
                    "name, building type, or 'Lawn'. Internal spaces become "
                    "underscores so the SampleID stays underscore-delimited."
                ),
                key="mielke_descriptor_input",
            )
        )

    elif protocol_choice == "PIIT":
        # PIIT: SiteID_[AM/PM_]PIIT_<Location(grid)>_Initials
        descriptor_label = "Location (grid)"
        descriptor_value = _sanitize_segment(
            st.text_input(
                "Location (grid)",
                placeholder="e.g. A1, A2, B1, B2",
                help="The grid cell within the site, e.g. A1 or B3.",
                key="piit_location_input",
            )
        )

    else:
        # Other / custom protocol: keep the legacy Position + Location combo
        # so existing workflows don't break. Joined with an underscore to
        # become a single descriptor segment in the SampleID.
        position_choice = st.radio(
            "Position",
            POSITION_OPTIONS,
            horizontal=True,
            key="position_choice",
        )
        if position_choice == "Other":
            position_value = st.text_input(
                "Specify position",
                placeholder="e.g. Driveway, Garden",
                key="position_other",
            ).strip()
        else:
            position_value = position_choice

        location_value = st.text_input(
            "Location (grid)",
            placeholder="e.g. A1, A2, B1, B2",
            help="The grid cell within the site, e.g. A1 or B3.",
            key="location_input",
        ).strip()

        descriptor_label = "Position + Location"
        if position_value and location_value:
            descriptor_value = (
                f"{_sanitize_segment(position_value)}_"
                f"{_sanitize_segment(location_value)}"
            )
        else:
            descriptor_value = ""  # Validation below will surface the gap.

    # ── Field crew initials ──
    initials_value = st.text_input(
        "Field Crew Initials",
        placeholder="e.g. JD",
        key="initials_input",
    ).strip()

    # ── Replicates ──
    replicates = st.number_input(
        "Number of replicates (rows to write for this SampleID)",
        min_value=1, max_value=10, value=3,
        help="Convention: 3 readings per sample, so 3 rows per SampleID.",
        key="replicates_input",
    )

    # ── Add button ──
    add_clicked = st.button(
        "➕ Add Sample", type="primary", use_container_width=True,
    )

    if add_clicked:
        missing = []
        if not site_id:                              missing.append("SiteID")
        if multi_site_today and not time_value:      missing.append("Time of Day")
        if not protocol_value:                       missing.append("Protocol")
        if not descriptor_value:                     missing.append(descriptor_label)
        if not initials_value:                       missing.append("Initials")

        if missing:
            st.warning(f"Missing required fields: {', '.join(missing)}.")
        else:
            sample_id = build_sample_id(
                site_id=site_id,
                time_of_day=time_value,
                protocol=protocol_value,
                descriptor=descriptor_value,
                initials=initials_value,
            )
            normalized_site_id = normalize_site_id(site_id)
            additions = [
                {"SiteID": normalized_site_id, "SampleID": sample_id}
                for _ in range(int(replicates))
            ]
            st.session_state.rows = pd.concat(
                [st.session_state.rows, pd.DataFrame(additions, columns=COLUMNS)],
                ignore_index=True,
            )
            # Stash a one-shot success message + trigger reset on next rerun.
            st.session_state["_last_added"] = (sample_id, int(replicates))
            st.session_state["_pending_reset"] = True
            st.rerun()


# ───────────────────────────────────────────────
#  RIGHT — PREVIEW + REVIEW
# ───────────────────────────────────────────────
with right_col:
    st.subheader("Preview")

    # One-shot success message after a successful add (survives the reset rerun).
    last_added = st.session_state.pop("_last_added", None)
    if last_added:
        sid, n = last_added
        st.success(f"Added {n} row(s):\n`{sid}`")

    # Live preview of the SampleID being built.
    # Time of Day is only required for the preview when multi-site is on.
    time_ok = (not multi_site_today) or bool(time_value)
    all_filled = all([
        site_id, time_ok, protocol_value, descriptor_value, initials_value,
    ])
    if all_filled:
        preview = build_sample_id(
            site_id=site_id,
            time_of_day=time_value,
            protocol=protocol_value,
            descriptor=descriptor_value,
            initials=initials_value,
        )
        st.info(f"**SampleID preview:**\n\n`{preview}`")
    else:
        st.caption("Fill all fields on the left to see a SampleID preview.")

    st.markdown("---")
    st.subheader("Review")

    current = st.session_state.rows

    m1, m2, m3 = st.columns(3)
    m1.metric("Total rows", len(current))
    m2.metric(
        "Unique SampleIDs",
        int(current["SampleID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
    )
    m3.metric(
        "Unique SiteIDs",
        int(current["SiteID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
    )

    if len(current):
        edited = st.data_editor(
            current[COLUMNS],
            num_rows="dynamic",
            use_container_width=True,
            hide_index=True,
            key="editor",
        )
        st.session_state.rows = edited.reindex(columns=COLUMNS).fillna("")
    else:
        st.info("No rows yet. Add some on the left.")


# ═══════════════════════════════════════════════
#  SAVE BAR (full-width below)
# ═══════════════════════════════════════════════
st.markdown("---")
st.subheader("Save")

col_save, col_clear, col_reload = st.columns(3)

with col_save:
    if st.button("💾 Save to disk", type="primary", use_container_width=True):
        try:
            write_field_csv(st.session_state.rows, OUTPUT_PATH)
            st.success(f"Saved {len(st.session_state.rows)} rows.")
        except Exception as e:
            st.error(f"Save failed: {e}")

with col_clear:
    if st.button("🗑️ Clear all (in-memory)", use_container_width=True):
        st.session_state.rows = pd.DataFrame(columns=COLUMNS)
        st.rerun()

with col_reload:
    if st.button("↻ Reload from disk", use_container_width=True):
        st.session_state.rows = load_existing_rows(OUTPUT_PATH)
        st.rerun()