# """
# field_entry.py — GroundSense Field Entry App

# A lightweight Streamlit form for recording field samples. Each sample's
# SampleID is auto-generated by joining structured fields with underscores.
# The exact format depends on the chosen protocol:

#     HUD     : SiteID_[AM/PM_]HUD_<Drip|Play|Yard>[Index]_Initials
#     MIELKE  : SiteID_[AM/PM_]MIELKE_<RoadName|BuildingType|Lawn>_Initials
#     PITT    : SiteID_[AM/PM_]PITT_[Front|Back_]<Location(grid)>_Initials
#     Other   : SiteID_[AM/PM_]<Protocol>_<Position>_<Location>_Initials  (legacy)

# The AM/PM segment is only included when the technician indicates that
# multiple sites are being sampled on the same day. For single-site days,
# Time of Day is omitted from the SampleID entirely.

# Layout
# ------
# Two columns, side-by-side:
#   • LEFT  — input fields (Protocol-driven; SiteID, AM/PM (conditional),
#             protocol-specific descriptor, Initials, Replicates)
#   • RIGHT — live SampleID preview + Review table of all rows

# After a successful "Add Sample", all input fields and toggles reset to
# their defaults so the next sample can be entered immediately — except
# SiteID, which is preserved so the technician can keep logging samples
# at the same site without retyping it.

# Output
# ------
# Writes `<repo>/data/site_databases/SiteID_SampleID.csv` —
# columns: SiteID, SampleID. This is the format the dashboard reads.
# """

# import csv
# import os
# from datetime import datetime

# import pandas as pd
# import streamlit as st


# # ═══════════════════════════════════════════════
# #  CONSTANTS
# # ═══════════════════════════════════════════════
# COLUMNS = ["SiteID", "SampleID"]
# OUTPUT_FILENAME = "SiteID_SampleID.csv"

# TIME_OPTIONS = ["AM", "PM", "Other"]
# POSITION_OPTIONS = ["Front", "Back", "Side", "Other"]
# PROTOCOL_OPTIONS = ["HUD", "PITT", "MIELKE", "Other"]
# HUD_DESCRIPTOR_OPTIONS = ["Drip", "Play", "Yard", "Other"]

# # Widget keys — kept in one place so the reset helper can target them precisely.
# WIDGET_KEYS = [
#     "site_id_input",
#     "multi_site_toggle",
#     "time_choice", "time_other",
#     "protocol_choice", "protocol_other",
#     "hud_descriptor_choice", "hud_descriptor_other", "hud_index_input",
#     "mielke_descriptor_input",
#     "pitt_yard_choice",
#     "pitt_location_input",
#     "position_choice", "position_other",
#     "location_input",
#     "initials_input",
#     "replicates_input",
# ]

# # Keys cleared after a successful "Add Sample". Intentionally excludes
# # `site_id_input` so the technician can stay on the same site and keep
# # logging samples without retyping the SiteID each time.
# RESET_WIDGET_KEYS = [k for k in WIDGET_KEYS if k != "site_id_input"]


# # ═══════════════════════════════════════════════
# #  PATH RESOLUTION
# # ═══════════════════════════════════════════════
# def get_repo_root() -> str:
#     """Return absolute path to the repo root (one level above /src)."""
#     return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


# def get_output_path() -> str:
#     """Where to write the field CSV — same place the dashboard reads from."""
#     return os.path.join(
#         get_repo_root(), "data", "site_databases", OUTPUT_FILENAME
#     )


# # ═══════════════════════════════════════════════
# #  EXISTING-DATA LOADER / WRITER
# # ═══════════════════════════════════════════════
# def load_existing_rows(path: str) -> pd.DataFrame:
#     """Load existing field CSV so users can append rather than overwrite."""
#     if not os.path.exists(path):
#         return pd.DataFrame(columns=COLUMNS)
#     try:
#         df = pd.read_csv(path, dtype=str).fillna("")
#         for c in COLUMNS:
#             if c not in df.columns:
#                 df[c] = ""
#         return df[COLUMNS]
#     except Exception as e:
#         st.warning(f"Could not parse existing CSV ({e}). Starting fresh.")
#         return pd.DataFrame(columns=COLUMNS)


# def write_field_csv(df: pd.DataFrame, path: str) -> None:
#     """Append session rows to the on-disk CSV without clobbering existing rows.

#     Re-reads disk right before writing, compares against the session
#     DataFrame on (SiteID, SampleID) tuples with replicate-count awareness,
#     and appends only the delta. This protects:
#       • Manually-prepended historical rows (your backfill case)
#       • Rows written by other Streamlit sessions while this one was open
#       • The replicate convention (3 identical rows per SampleID stay 3)

#     Writes atomically (tempfile + os.replace) so a crash or SharePoint
#     sync lock mid-write can't corrupt the file.
#     """
#     import tempfile, time
#     os.makedirs(os.path.dirname(path), exist_ok=True)
#     session_rows = df.reindex(columns=COLUMNS).fillna("")

#     last_err = None
#     for attempt in range(5):
#         try:
#             on_disk = load_existing_rows(path)

#             # Replicate-aware delta: how many of each (SiteID, SampleID)
#             # pair does the session have that disk doesn't?
#             disk_counts = (
#                 on_disk.groupby(COLUMNS).size()
#                 if len(on_disk) else pd.Series(dtype=int)
#             )
#             sess_counts = (
#                 session_rows.groupby(COLUMNS).size()
#                 if len(session_rows) else pd.Series(dtype=int)
#             )

#             to_append = []
#             for key, n_sess in sess_counts.items():
#                 n_disk = int(disk_counts.get(key, 0))
#                 delta = int(n_sess) - n_disk
#                 if delta > 0:
#                     site_id, sample_id = key
#                     to_append.extend(
#                         [{"SiteID": site_id, "SampleID": sample_id}] * delta
#                     )

#             if not to_append:
#                 return  # Nothing new; leave disk untouched.

#             combined = pd.concat(
#                 [on_disk, pd.DataFrame(to_append, columns=COLUMNS)],
#                 ignore_index=True,
#             ).reindex(columns=COLUMNS).fillna("")

#             # Atomic write
#             dir_ = os.path.dirname(path)
#             fd, tmp_path = tempfile.mkstemp(prefix=".tmp_", suffix=".csv", dir=dir_)
#             try:
#                 with os.fdopen(fd, "w", newline="", encoding="utf-8") as f:
#                     writer = csv.writer(f)
#                     writer.writerow(COLUMNS)
#                     for _, row in combined.iterrows():
#                         writer.writerow([row.get(c, "") for c in COLUMNS])
#                 os.replace(tmp_path, path)
#             except Exception:
#                 if os.path.exists(tmp_path):
#                     try: os.remove(tmp_path)
#                     except OSError: pass
#                 raise
#             return

#         except PermissionError as e:
#             last_err = e
#             time.sleep(0.5 * (2 ** attempt))
#     raise RuntimeError(
#         f"Could not write {path} after 5 attempts (likely SharePoint "
#         f"sync lock). Last error: {last_err}"
#     )


# # ═══════════════════════════════════════════════
# #  SAMPLE ID BUILDER
# # ═══════════════════════════════════════════════
# def normalize_site_id(raw: str) -> str:
#     """Zero-pad SiteID if it looks like a date.

#     The convention is sampling date in ISO form (YYYY-MM-DD). Technicians
#     sometimes type non-padded dates like '2025-6-24'; we silently canonicalize
#     to '2025-06-24' so downstream lookups against site_configs.json (which
#     stores the padded form) succeed.

#     Non-date SiteIDs (e.g. legacy 'PITT_24June2025') are returned unchanged.
#     """
#     s = (raw or "").strip()
#     if not s:
#         return s
#     parts = s.split("-")
#     if len(parts) == 3 and all(p.isdigit() for p in parts):
#         y, m, d = parts
#         if len(y) == 4 and 1 <= int(m) <= 12 and 1 <= int(d) <= 31:
#             try:
#                 # Validate it's a real calendar date (catches Feb 30 etc.)
#                 datetime(int(y), int(m), int(d))
#                 return f"{int(y):04d}-{int(m):02d}-{int(d):02d}"
#             except ValueError:
#                 return s
#     return s


# def _sanitize_segment(s: str) -> str:
#     """Make a free-text field safe to drop into an underscore-joined ID.

#     Strips leading/trailing whitespace and replaces any internal whitespace
#     runs with single underscores so 'Front Yard' becomes 'Front_Yard'.
#     Without this, internal spaces would survive into the SampleID and break
#     parsing assumptions elsewhere in the pipeline.
#     """
#     return "_".join((s or "").strip().split())


# def build_sample_id(
#     site_id: str,
#     time_of_day: str,       # "" means omit (single-site day)
#     protocol: str,
#     descriptor: str,        # protocol-specific middle segment(s); already sanitized
#     initials: str,
# ) -> str:
#     """Join the structured fields with underscores to form the SampleID.

#     Format: SiteID_[TimeOfDay_]Protocol_Descriptor_Initials

#     `time_of_day` is included only when non-empty; this is how the
#     "single site today" case omits AM/PM. `descriptor` is whatever
#     protocol-specific middle segment(s) the caller built (already
#     sanitized and underscore-joined if multi-part). SiteID is normalized
#     via normalize_site_id() so date-like SiteIDs get zero-padded consistently.
#     """
#     parts = [normalize_site_id(site_id)]
#     if time_of_day:
#         parts.append(time_of_day.strip())
#     parts.extend([protocol.strip(), descriptor.strip(), initials.strip()])
#     return "_".join(parts)


# # ═══════════════════════════════════════════════
# #  PAGE
# # ═══════════════════════════════════════════════
# st.set_page_config(
#     page_title="Urban Soil Co-Lab Field Entry",
#     page_icon="🌱",
#     layout="wide",
# )

# st.title("🌱 Field Sample Entry")
# st.caption(
#     "Record SiteID and SampleIDs from the field."
# )

# OUTPUT_PATH = get_output_path()


# # ─── Session state init ───
# if "rows" not in st.session_state:
#     st.session_state.rows = load_existing_rows(OUTPUT_PATH)

# # Flag set by the "Add Sample" handler; consumed at the top of the next
# # rerun to wipe widget state. We can't mutate widget keys after they've
# # been instantiated in the same run, so we do it on the *next* run.
# if st.session_state.get("_pending_reset"):
#     for k in RESET_WIDGET_KEYS:
#         if k in st.session_state:
#             del st.session_state[k]
#     st.session_state["_pending_reset"] = False


# # ═══════════════════════════════════════════════
# #  TWO-COLUMN LAYOUT — inputs left, preview right
# # ═══════════════════════════════════════════════
# left_col, right_col = st.columns([1, 1], gap="large")


# # ───────────────────────────────────────────────
# #  LEFT — INPUTS
# # ───────────────────────────────────────────────
# with left_col:
#     st.subheader("Sample Entry")

#     # ── SiteID ──
#     site_id = st.text_input(
#         "SiteID",
#         help="Free-form. Convention: sampling date as YYYY-M-D, e.g. 2025-10-18.",
#         key="site_id_input",
#     ).strip()

#     # ── Multiple sites today? ──
#     # Controls whether AM/PM is included in the SampleID. Default off
#     # (most days are single-site); technician flips it on when they know
#     # they'll be sampling more than one site that day.
#     multi_site_today = st.checkbox(
#         "Multiple sites sampled today (include AM/PM in SampleID)",
#         value=False,
#         key="multi_site_toggle",
#         help=(
#             "Off → SampleID has no AM/PM segment. "
#             "On → AM/PM is required and appears in the SampleID."
#         ),
#     )

#     # ── Time of Day (only when multi-site) ──
#     if multi_site_today:
#         time_choice = st.radio(
#             "Time of Day",
#             TIME_OPTIONS,
#             horizontal=True,
#             key="time_choice",
#         )
#         if time_choice == "Other":
#             time_value = st.text_input(
#                 "Specify time of day",
#                 placeholder="e.g. Dawn, Dusk",
#                 key="time_other",
#             ).strip()
#         else:
#             time_value = time_choice
#     else:
#         time_value = ""  # Omitted from the SampleID for single-site days.

#     # ── Protocol (drives the rest of the form) ──
#     protocol_choice = st.radio(
#         "Protocol",
#         PROTOCOL_OPTIONS,
#         horizontal=True,
#         key="protocol_choice",
#     )
#     if protocol_choice == "Other":
#         protocol_value = st.text_input(
#             "Specify protocol",
#             placeholder="e.g. Custom",
#             key="protocol_other",
#         ).strip()
#     else:
#         protocol_value = protocol_choice

#     # ── Protocol-specific descriptor fields ──
#     # Each branch sets `descriptor_value` (the middle segment that goes
#     # between the protocol name and the initials in the SampleID), plus
#     # a human-readable `descriptor_label` for the "missing fields" warning.
#     descriptor_value = ""
#     descriptor_label = "Descriptor"

#     if protocol_choice == "HUD":
#         # HUD: SiteID_[AM/PM_]HUD_<Drip|Play|Yard>[Index]_Initials
#         # When a site has multiple instances of the same descriptor (e.g.
#         # three drip lines, two yards), the technician picks a non-zero
#         # index and it gets concatenated directly onto the descriptor:
#         # Drip + 1 → "Drip1", Yard + 2 → "Yard2". Index 0 is the "no number"
#         # default — descriptor stays bare.
#         descriptor_label = "HUD Location"
#         hud_choice = st.radio(
#             "HUD Location",
#             HUD_DESCRIPTOR_OPTIONS,
#             horizontal=True,
#             key="hud_descriptor_choice",
#             help="Drip line, Play area, or Yard. Use 'Other' if none fit.",
#         )
#         if hud_choice == "Other":
#             hud_base = _sanitize_segment(
#                 st.text_input(
#                     "Specify HUD location",
#                     placeholder="e.g. Garden",
#                     key="hud_descriptor_other",
#                 )
#             )
#         else:
#             hud_base = hud_choice

#         # Optional numeric index. number_input is the right widget here:
#         # it has compact + / – step buttons on the right edge of the box
#         # itself (same look as "Number of replicates" below), and it
#         # accepts typed values for indexes beyond what stepping would
#         # reach. 0 means "no number appended" — we display the help text
#         # to that effect rather than trying to relabel 0 as "None" inside
#         # the number widget.
#         hud_index = st.number_input(
#             "Index (0 = no number)",
#             min_value=0, max_value=99, value=0, step=1,
#             help=(
#                 "Use when a site has multiple of the same HUD location, "
#                 "e.g. Drip1, Drip2, Drip3 or Yard1, Yard2. Use the + / – "
#                 "buttons or type a value. Leave at 0 when there's only "
#                 "one and no number is needed."
#             ),
#             key="hud_index_input",
#         )

#         if hud_base and int(hud_index) > 0:
#             descriptor_value = f"{hud_base}{int(hud_index)}"
#         else:
#             descriptor_value = hud_base

#     elif protocol_choice == "MIELKE":
#         # MIELKE: SiteID_[AM/PM_]MIELKE_<RoadName|BuildingType|Lawn>_Initials
#         descriptor_label = "Mielke Descriptor"
#         descriptor_value = _sanitize_segment(
#             st.text_input(
#                 "Road Name / Building Type / Lawn",
#                 placeholder="e.g. MainSt, ResidentialHouse, Lawn",
#                 help=(
#                     "Whichever descriptor fits the sample location: a road "
#                     "name, building type, or 'Lawn'. Internal spaces become "
#                     "underscores so the SampleID stays underscore-delimited."
#                 ),
#                 key="mielke_descriptor_input",
#             )
#         )

#     elif protocol_choice == "PITT":
#         # PITT: SiteID_[AM/PM_]PITT_[Front|Back_]<Location(grid)>_Initials
#         descriptor_label = "Location (grid)"

#         # Optional Front/Back yard segment — appears before the grid cell.
#         # "Not specified" keeps the SampleID identical to the legacy format
#         # so existing data and matching patterns continue to work.
#         pitt_yard_choice = st.radio(
#             "Yard (optional)",
#             ["Not specified", "Front", "Back"],
#             horizontal=True,
#             help=(
#                 "Optional. When picked, the yard is recorded in the SampleID "
#                 "as a separate segment before the grid cell (e.g. "
#                 "Front_A1 or Back_B3). Leave on 'Not specified' to keep the "
#                 "SampleID free of a yard tag."
#             ),
#             key="pitt_yard_choice",
#         )

#         grid_value = _sanitize_segment(
#             st.text_input(
#                 "Location (grid)",
#                 placeholder="e.g. A1, A2, B1, B2",
#                 help="The grid cell within the site, e.g. A1 or B3.",
#                 key="pitt_location_input",
#             )
#         )

#         # Build the descriptor: prepend the yard with an underscore only
#         # when the technician actually picked one. Empty grid stays empty
#         # so the missing-fields warning still fires correctly.
#         if pitt_yard_choice in ("Front", "Back") and grid_value:
#             descriptor_value = f"{pitt_yard_choice}_{grid_value}"
#         else:
#             descriptor_value = grid_value

#     else:
#         # Other / custom protocol: keep the legacy Position + Location combo
#         # so existing workflows don't break. Joined with an underscore to
#         # become a single descriptor segment in the SampleID.
#         position_choice = st.radio(
#             "Position",
#             POSITION_OPTIONS,
#             horizontal=True,
#             key="position_choice",
#         )
#         if position_choice == "Other":
#             position_value = st.text_input(
#                 "Specify position",
#                 placeholder="e.g. Driveway, Garden",
#                 key="position_other",
#             ).strip()
#         else:
#             position_value = position_choice

#         location_value = st.text_input(
#             "Location (grid)",
#             placeholder="e.g. A1, A2, B1, B2",
#             help="The grid cell within the site, e.g. A1 or B3.",
#             key="location_input",
#         ).strip()

#         descriptor_label = "Position + Location"
#         if position_value and location_value:
#             descriptor_value = (
#                 f"{_sanitize_segment(position_value)}_"
#                 f"{_sanitize_segment(location_value)}"
#             )
#         else:
#             descriptor_value = ""  # Validation below will surface the gap.

#     # ── Field crew initials ──
#     initials_value = st.text_input(
#         "Field Crew Initials",
#         placeholder="e.g. JD",
#         key="initials_input",
#     ).strip()

#     # ── Replicates ──
#     replicates = st.number_input(
#         "Number of replicates (rows to write for this SampleID)",
#         min_value=1, max_value=10, value=3,
#         help="Convention: 3 readings per sample, so 3 rows per SampleID.",
#         key="replicates_input",
#     )

#     # ── Add button ──
#     add_clicked = st.button(
#         "➕ Add Sample", type="primary", use_container_width=True,
#     )

#     if add_clicked:
#         missing = []
#         if not site_id:                              missing.append("SiteID")
#         if multi_site_today and not time_value:      missing.append("Time of Day")
#         if not protocol_value:                       missing.append("Protocol")
#         if not descriptor_value:                     missing.append(descriptor_label)
#         if not initials_value:                       missing.append("Initials")

#         if missing:
#             st.warning(f"Missing required fields: {', '.join(missing)}.")
#         else:
#             sample_id = build_sample_id(
#                 site_id=site_id,
#                 time_of_day=time_value,
#                 protocol=protocol_value,
#                 descriptor=descriptor_value,
#                 initials=initials_value,
#             )
#             normalized_site_id = normalize_site_id(site_id)
#             additions = [
#                 {"SiteID": normalized_site_id, "SampleID": sample_id}
#                 for _ in range(int(replicates))
#             ]
#             st.session_state.rows = pd.concat(
#                 [st.session_state.rows, pd.DataFrame(additions, columns=COLUMNS)],
#                 ignore_index=True,
#             )
#             # Stash a one-shot success message + trigger reset on next rerun.
#             st.session_state["_last_added"] = (sample_id, int(replicates))
#             st.session_state["_pending_reset"] = True
#             st.rerun()


# # ───────────────────────────────────────────────
# #  RIGHT — PREVIEW + REVIEW
# # ───────────────────────────────────────────────
# with right_col:
#     st.subheader("Preview")

#     # One-shot success message after a successful add (survives the reset rerun).
#     last_added = st.session_state.pop("_last_added", None)
#     if last_added:
#         sid, n = last_added
#         st.success(f"Added {n} row(s):\n`{sid}`")

#     # Live preview of the SampleID being built.
#     # Time of Day is only required for the preview when multi-site is on.
#     time_ok = (not multi_site_today) or bool(time_value)
#     all_filled = all([
#         site_id, time_ok, protocol_value, descriptor_value, initials_value,
#     ])
#     if all_filled:
#         preview = build_sample_id(
#             site_id=site_id,
#             time_of_day=time_value,
#             protocol=protocol_value,
#             descriptor=descriptor_value,
#             initials=initials_value,
#         )
#         st.info(f"**SampleID preview:**\n\n`{preview}`")
#     else:
#         st.caption("Fill all fields on the left to see a SampleID preview.")

#     st.markdown("---")
#     st.subheader("Review")

#     current = st.session_state.rows

#     m1, m2, m3 = st.columns(3)
#     m1.metric("Total rows", len(current))
#     m2.metric(
#         "Unique SampleIDs",
#         int(current["SampleID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
#     )
#     m3.metric(
#         "Unique SiteIDs",
#         int(current["SiteID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
#     )

#     if len(current):
#         edited = st.data_editor(
#             current[COLUMNS],
#             num_rows="dynamic",
#             use_container_width=True,
#             hide_index=True,
#             key="editor",
#         )
#         st.session_state.rows = edited.reindex(columns=COLUMNS).fillna("")
#     else:
#         st.info("No rows yet. Add some on the left.")


# # ═══════════════════════════════════════════════
# #  SAVE BAR (full-width below)
# # ═══════════════════════════════════════════════
# st.markdown("---")
# st.subheader("Save")

# col_save, col_clear, col_reload = st.columns(3)

# with col_save:
#     if st.button("💾 Save to disk", type="primary", use_container_width=True):
#         try:
#             write_field_csv(st.session_state.rows, OUTPUT_PATH)
#             st.success(f"Saved {len(st.session_state.rows)} rows.")
#         except Exception as e:
#             st.error(f"Save failed: {e}")

# with col_clear:
#     if st.button("🗑️ Clear all (in-memory)", use_container_width=True):
#         st.session_state.rows = pd.DataFrame(columns=COLUMNS)
#         st.rerun()

# with col_reload:
#     if st.button("↻ Reload from disk", use_container_width=True):
#         st.session_state.rows = load_existing_rows(OUTPUT_PATH)
#         st.rerun()

import csv
import os
from datetime import datetime
 
import pandas as pd
import streamlit as st
 
 
# ═══════════════════════════════════════════════
#  CONSTANTS
# ═══════════════════════════════════════════════
COLUMNS = ["SiteID", "SampleID", "Notes"]
OUTPUT_FILENAME = "SiteID_SampleID.csv"
 
TIME_OPTIONS = ["AM", "PM", "Other"]
POSITION_OPTIONS = ["Front", "Back", "Side", "Other"]
PROTOCOL_OPTIONS = ["HUD", "PITT", "MIELKE", "Other"]
HUD_DESCRIPTOR_OPTIONS = ["Drip", "Play", "Yard", "Other"]
 
# Widget keys — kept in one place so the reset helper can target them precisely.
WIDGET_KEYS = [
    "site_id_input",
    "multi_site_toggle",
    "time_choice", "time_other",
    "protocol_choice", "protocol_other",
    "hud_descriptor_choice", "hud_descriptor_other", "hud_index_input",
    "mielke_descriptor_input",
    "pitt_yard_choice",
    "pitt_location_input",
    "position_choice", "position_other",
    "location_input",
    "custom_label_input",
    "initials_input",
    "notes_input",
    "replicates_input",
]
 
# Keys cleared after a successful "Add Sample".
#
# Intentionally PRESERVES the fields a technician is holding steady across
# many samples at one site:
#   • site_id_input      — same site all session
#   • multi_site_toggle  — AM/PM decision is per-day, not per-sample
#   • protocol_choice / protocol_other — same protocol run-to-run
#   • initials_input     — same crew all session
#
# Preserving protocol_choice is also what fixes the "HUD options flash on a
# non-HUD protocol after Add" bug: deleting that key reset the radio to its
# first option (HUD), so the HUD branch rendered for one frame. Keeping it
# means the form stays on your chosen protocol after every Add.
_PRESERVE_ON_RESET = {
    "site_id_input",
    "multi_site_toggle",
    "protocol_choice", "protocol_other",
    "initials_input",
}
RESET_WIDGET_KEYS = [k for k in WIDGET_KEYS if k not in _PRESERVE_ON_RESET]
 
 
# ═══════════════════════════════════════════════
#  PATH RESOLUTION
# ═══════════════════════════════════════════════
def get_repo_root() -> str:
    """Return absolute path to the repo root (one level above /src)."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
 
 
def get_output_path() -> str:
    """Where to write the field CSV — same place the dashboard reads from."""
    return os.path.join(
        get_repo_root(), "data", "site_databases", OUTPUT_FILENAME
    )
 
 
# ═══════════════════════════════════════════════
#  EXISTING-DATA LOADER / WRITER
# ═══════════════════════════════════════════════
def load_existing_rows(path: str) -> pd.DataFrame:
    """Load existing field CSV so users can append rather than overwrite.
 
    Backfills any missing column (notably `Notes`, which older CSVs written
    before the Notes feature won't have) with empty strings so historical
    files load cleanly.
    """
    if not os.path.exists(path):
        return pd.DataFrame(columns=COLUMNS)
    try:
        df = pd.read_csv(path, dtype=str).fillna("")
        for c in COLUMNS:
            if c not in df.columns:
                df[c] = ""
        return df[COLUMNS]
    except Exception as e:
        st.warning(f"Could not parse existing CSV ({e}). Starting fresh.")
        return pd.DataFrame(columns=COLUMNS)
 
 
def write_field_csv(df: pd.DataFrame, path: str) -> int:
    """Append session rows to the on-disk CSV without clobbering existing rows.
 
    Re-reads disk right before writing, compares against the session
    DataFrame on (SiteID, SampleID) tuples with replicate-count awareness,
    and appends only the delta. Notes travel with each appended row.
 
    Returns the number of NEW rows actually written to disk (0 if the
    session held nothing that wasn't already saved). Writes atomically
    (tempfile + os.replace) so a crash or SharePoint sync lock mid-write
    can't corrupt the file.
    """
    import tempfile, time
    os.makedirs(os.path.dirname(path), exist_ok=True)
    session_rows = df.reindex(columns=COLUMNS).fillna("")
 
    last_err = None
    for attempt in range(5):
        try:
            on_disk = load_existing_rows(path)
 
            # Replicate-aware delta on (SiteID, SampleID). Notes is carried
            # along but not part of the identity key — two rows with the
            # same SiteID+SampleID are the same sample regardless of note.
            key_cols = ["SiteID", "SampleID"]
            disk_counts = (
                on_disk.groupby(key_cols).size()
                if len(on_disk) else pd.Series(dtype=int)
            )
            sess_grp = (
                session_rows.groupby(key_cols)
                if len(session_rows) else None
            )
            sess_counts = (
                sess_grp.size() if sess_grp is not None else pd.Series(dtype=int)
            )
 
            to_append = []
            for key, n_sess in sess_counts.items():
                n_disk = int(disk_counts.get(key, 0))
                delta = int(n_sess) - n_disk
                if delta > 0:
                    site_id, sample_id = key
                    # Carry the note from this group's session rows (first
                    # non-empty wins; blank if none).
                    grp = session_rows[
                        (session_rows["SiteID"] == site_id)
                        & (session_rows["SampleID"] == sample_id)
                    ]
                    note_vals = [n for n in grp["Notes"].tolist() if str(n).strip()]
                    note = note_vals[0] if note_vals else ""
                    to_append.extend(
                        [{"SiteID": site_id, "SampleID": sample_id, "Notes": note}]
                        * delta
                    )
 
            if not to_append:
                return 0  # Nothing new; leave disk untouched.
 
            combined = pd.concat(
                [on_disk, pd.DataFrame(to_append, columns=COLUMNS)],
                ignore_index=True,
            ).reindex(columns=COLUMNS).fillna("")
 
            # Atomic write
            dir_ = os.path.dirname(path)
            fd, tmp_path = tempfile.mkstemp(prefix=".tmp_", suffix=".csv", dir=dir_)
            try:
                with os.fdopen(fd, "w", newline="", encoding="utf-8") as f:
                    writer = csv.writer(f)
                    writer.writerow(COLUMNS)
                    for _, row in combined.iterrows():
                        writer.writerow([row.get(c, "") for c in COLUMNS])
                os.replace(tmp_path, path)
            except Exception:
                if os.path.exists(tmp_path):
                    try: os.remove(tmp_path)
                    except OSError: pass
                raise
            return len(to_append)
 
        except PermissionError as e:
            last_err = e
            time.sleep(0.5 * (2 ** attempt))
    raise RuntimeError(
        f"Could not write {path} after 5 attempts (likely SharePoint "
        f"sync lock). Last error: {last_err}"
    )
 
 
# ═══════════════════════════════════════════════
#  SAMPLE ID BUILDER
# ═══════════════════════════════════════════════
def normalize_site_id(raw: str) -> str:
    """Zero-pad SiteID if it looks like a date (YYYY-M-D → YYYY-MM-DD)."""
    s = (raw or "").strip()
    if not s:
        return s
    parts = s.split("-")
    if len(parts) == 3 and all(p.isdigit() for p in parts):
        y, m, d = parts
        if len(y) == 4 and 1 <= int(m) <= 12 and 1 <= int(d) <= 31:
            try:
                datetime(int(y), int(m), int(d))
                return f"{int(y):04d}-{int(m):02d}-{int(d):02d}"
            except ValueError:
                return s
    return s
 
 
def _sanitize_segment(s: str) -> str:
    """Make a free-text field safe to drop into an underscore-joined ID."""
    return "_".join((s or "").strip().split())
 
 
def build_sample_id(
    site_id: str,
    time_of_day: str,       # "" means omit (single-site day)
    protocol: str,
    descriptor: str,        # protocol-specific middle segment(s); already sanitized
    initials: str,
) -> str:
    """Join the structured fields with underscores to form the SampleID.
 
    Format: SiteID_[TimeOfDay_]Protocol_Descriptor_Initials
    """
    parts = [normalize_site_id(site_id)]
    if time_of_day:
        parts.append(time_of_day.strip())
    parts.extend([protocol.strip(), descriptor.strip(), initials.strip()])
    return "_".join(parts)
 
 
# ═══════════════════════════════════════════════
#  PAGE
# ═══════════════════════════════════════════════
st.set_page_config(
    page_title="Urban Soil Co-Lab Field Entry",
    page_icon="🌱",
    layout="wide",
)
 
st.title("🌱 Field Sample Entry")
st.caption(
    "Record SiteID and SampleIDs from the field."
)
 
OUTPUT_PATH = get_output_path()
 
 
# ─── Session state init ───
if "rows" not in st.session_state:
    st.session_state.rows = load_existing_rows(OUTPUT_PATH)
 
# Track how many rows in memory are already safely on disk, so the Save
# bar can show clearly whether there are UNSAVED entries.
if "saved_row_count" not in st.session_state:
    st.session_state.saved_row_count = len(st.session_state.rows)
 
# Flag set by the "Add Sample" handler; consumed at the top of the next
# rerun to wipe the per-sample widget state (preserving site/protocol/etc).
if st.session_state.get("_pending_reset"):
    for k in RESET_WIDGET_KEYS:
        if k in st.session_state:
            del st.session_state[k]
    st.session_state["_pending_reset"] = False
 
 
# ═══════════════════════════════════════════════
#  TWO-COLUMN LAYOUT — inputs left, preview right
# ═══════════════════════════════════════════════
left_col, right_col = st.columns([1, 1], gap="large")
 
 
# ───────────────────────────────────────────────
#  LEFT — INPUTS
# ───────────────────────────────────────────────
with left_col:
    st.subheader("Sample Entry")
 
    # ── SiteID ──
    site_id = st.text_input(
        "SiteID",
        help="Free-form. Convention: sampling date as YYYY-M-D, e.g. 2025-10-18.",
        key="site_id_input",
    ).strip()
 
    # ── Multiple sites today? ──
    multi_site_today = st.checkbox(
        "Multiple sites sampled today (include AM/PM in SampleID)",
        value=False,
        key="multi_site_toggle",
        help=(
            "Off → SampleID has no AM/PM segment. "
            "On → AM/PM is required and appears in the SampleID."
        ),
    )
 
    # ── Time of Day (only when multi-site) ──
    if multi_site_today:
        time_choice = st.radio(
            "Time of Day",
            TIME_OPTIONS,
            horizontal=True,
            key="time_choice",
        )
        if time_choice == "Other":
            time_value = st.text_input(
                "Specify time of day",
                placeholder="e.g. Dawn, Dusk",
                key="time_other",
            ).strip()
        else:
            time_value = time_choice
    else:
        time_value = ""  # Omitted from the SampleID for single-site days.
 
    # ── Protocol (drives the rest of the form) ──
    protocol_choice = st.radio(
        "Protocol",
        PROTOCOL_OPTIONS,
        horizontal=True,
        key="protocol_choice",
    )
    if protocol_choice == "Other":
        protocol_value = st.text_input(
            "Specify protocol",
            placeholder="e.g. Custom",
            key="protocol_other",
        ).strip()
    else:
        protocol_value = protocol_choice
 
    # ── Protocol-specific descriptor fields ──
    descriptor_value = ""
    descriptor_label = "Descriptor"
 
    if protocol_choice == "HUD":
        descriptor_label = "HUD Location"
        hud_choice = st.radio(
            "HUD Location",
            HUD_DESCRIPTOR_OPTIONS,
            horizontal=True,
            key="hud_descriptor_choice",
            help="Drip line, Play area, or Yard. Use 'Other' if none fit.",
        )
        if hud_choice == "Other":
            hud_base = _sanitize_segment(
                st.text_input(
                    "Specify HUD location",
                    placeholder="e.g. Garden",
                    key="hud_descriptor_other",
                )
            )
        else:
            hud_base = hud_choice
 
        hud_index = st.number_input(
            "Index (0 = no number)",
            min_value=0, max_value=99, value=0, step=1,
            help=(
                "Use when a site has multiple of the same HUD location, "
                "e.g. Drip1, Drip2, Drip3 or Yard1, Yard2. Use the + / – "
                "buttons or type a value. Leave at 0 when there's only "
                "one and no number is needed."
            ),
            key="hud_index_input",
        )
 
        if hud_base and int(hud_index) > 0:
            descriptor_value = f"{hud_base}{int(hud_index)}"
        else:
            descriptor_value = hud_base
 
    elif protocol_choice == "MIELKE":
        descriptor_label = "Mielke Descriptor"
        descriptor_value = _sanitize_segment(
            st.text_input(
                "Road Name / Building Type / Lawn",
                placeholder="e.g. MainSt, ResidentialHouse, Lawn",
                help=(
                    "Whichever descriptor fits the sample location: a road "
                    "name, building type, or 'Lawn'. Internal spaces become "
                    "underscores so the SampleID stays underscore-delimited."
                ),
                key="mielke_descriptor_input",
            )
        )
 
    elif protocol_choice == "PITT":
        descriptor_label = "Location (grid)"
 
        pitt_yard_choice = st.radio(
            "Yard (optional)",
            ["Not specified", "Front", "Back"],
            horizontal=True,
            help=(
                "Optional. When picked, the yard is recorded in the SampleID "
                "as a separate segment before the grid cell (e.g. "
                "Front_A1 or Back_B3). Leave on 'Not specified' to keep the "
                "SampleID free of a yard tag."
            ),
            key="pitt_yard_choice",
        )
 
        grid_value = _sanitize_segment(
            st.text_input(
                "Location (grid)",
                placeholder="e.g. A1, A2, B1, B2",
                help="The grid cell within the site, e.g. A1 or B3.",
                key="pitt_location_input",
            )
        )
 
        if pitt_yard_choice in ("Front", "Back") and grid_value:
            descriptor_value = f"{pitt_yard_choice}_{grid_value}"
        else:
            descriptor_value = grid_value
 
    else:
        # Other / custom protocol.
        #
        # Simplified per field feedback: a single free-text Label is all
        # that's needed. Examples: "Fill-Pile", "Raised-Bed". The label is
        # sanitized (spaces → underscores) and dropped straight into the
        # SampleID as the descriptor segment, e.g.
        #   2026-07-31_Other_Fill-Pile_JD
        descriptor_label = "Label"
        descriptor_value = _sanitize_segment(
            st.text_input(
                "Label",
                placeholder="e.g. Fill-Pile, Raised-Bed",
                help=(
                    "A short free-text label for this custom sample. "
                    "Spaces become underscores. Example: Fill-Pile → "
                    "…_Other_Fill-Pile_…"
                ),
                key="custom_label_input",
            )
        )
 
    # ── Field crew initials ──
    initials_value = st.text_input(
        "Field Crew Initials",
        placeholder="e.g. JD",
        key="initials_input",
    ).strip()
 
    # ── Notes (optional, all protocols) ──
    notes_value = st.text_input(
        "Notes (optional)",
        placeholder="e.g. Brick, asphalt, paint chips",
        help=(
            "Optional free-text notes about this sample — surface material, "
            "debris, anything you'd otherwise only write on paper. Saved "
            "alongside the SampleID."
        ),
        key="notes_input",
    ).strip()
 
    # ── Replicates ──
    replicates = st.number_input(
        "Number of replicates (rows to write for this SampleID)",
        min_value=1, max_value=10, value=3,
        help="Convention: 3 readings per sample, so 3 rows per SampleID.",
        key="replicates_input",
    )
 
    # ── Add button ──
    add_clicked = st.button(
        "➕ Add Sample", type="primary", use_container_width=True,
    )
 
    if add_clicked:
        missing = []
        if not site_id:                              missing.append("SiteID")
        if multi_site_today and not time_value:      missing.append("Time of Day")
        if not protocol_value:                       missing.append("Protocol")
        if not descriptor_value:                     missing.append(descriptor_label)
        if not initials_value:                       missing.append("Initials")
 
        if missing:
            st.warning(f"Missing required fields: {', '.join(missing)}.")
        else:
            sample_id = build_sample_id(
                site_id=site_id,
                time_of_day=time_value,
                protocol=protocol_value,
                descriptor=descriptor_value,
                initials=initials_value,
            )
            normalized_site_id = normalize_site_id(site_id)
            additions = [
                {
                    "SiteID": normalized_site_id,
                    "SampleID": sample_id,
                    "Notes": notes_value,
                }
                for _ in range(int(replicates))
            ]
            st.session_state.rows = pd.concat(
                [st.session_state.rows, pd.DataFrame(additions, columns=COLUMNS)],
                ignore_index=True,
            )
            # Stash a one-shot success message + trigger reset on next rerun.
            st.session_state["_last_added"] = (sample_id, int(replicates))
            st.session_state["_pending_reset"] = True
            st.rerun()
 
 
# ───────────────────────────────────────────────
#  RIGHT — PREVIEW + REVIEW
# ───────────────────────────────────────────────
with right_col:
    st.subheader("Preview")
 
    # One-shot success message after a successful add (survives the reset rerun).
    last_added = st.session_state.pop("_last_added", None)
    if last_added:
        sid, n = last_added
        st.success(f"Added {n} row(s):\n`{sid}`")
 
    # Live preview of the SampleID being built.
    time_ok = (not multi_site_today) or bool(time_value)
    all_filled = all([
        site_id, time_ok, protocol_value, descriptor_value, initials_value,
    ])
    if all_filled:
        preview = build_sample_id(
            site_id=site_id,
            time_of_day=time_value,
            protocol=protocol_value,
            descriptor=descriptor_value,
            initials=initials_value,
        )
        st.info(f"**SampleID preview:**\n\n`{preview}`")
    else:
        st.caption("Fill all fields on the left to see a SampleID preview.")
 
    st.markdown("---")
    st.subheader("Review")
    st.caption("Newest entries at the top. Edit cells directly; changes are kept in memory until you Save.")
 
    current = st.session_state.rows
 
    m1, m2, m3 = st.columns(3)
    m1.metric("Total rows", len(current))
    m2.metric(
        "Unique SampleIDs",
        int(current["SampleID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
    )
    m3.metric(
        "Unique SiteIDs",
        int(current["SiteID"].replace("", pd.NA).dropna().nunique()) if len(current) else 0,
    )
 
    if len(current):
        # Show newest-first so the most recent entry is visible without
        # scrolling. We reverse for display, let the user edit, then map
        # the edited (reversed) frame back to storage order before saving
        # to session_state so row identity/order on disk is preserved.
        display_df = current[COLUMNS].iloc[::-1].reset_index(drop=True)
 
        edited = st.data_editor(
            display_df,
            num_rows="dynamic",
            use_container_width=True,
            hide_index=True,
            key="editor",
            column_config={
                "SiteID": st.column_config.TextColumn("SiteID", width="medium"),
                "SampleID": st.column_config.TextColumn("SampleID", width="large"),
                "Notes": st.column_config.TextColumn("Notes", width="medium"),
            },
        )
 
        # Un-reverse back to storage order and commit to session_state.
        committed = edited.reindex(columns=COLUMNS).fillna("").iloc[::-1].reset_index(drop=True)
        st.session_state.rows = committed
    else:
        st.info("No rows yet. Add some on the left.")
 
 
# ═══════════════════════════════════════════════
#  SAVE BAR (full-width below)
# ═══════════════════════════════════════════════
st.markdown("---")
 
# Unsaved-work indicator. saved_row_count tracks how many rows are known
# to be on disk; anything beyond that in memory is unsaved.
n_rows = len(st.session_state.rows)
n_saved = st.session_state.get("saved_row_count", 0)
has_unsaved = n_rows != n_saved
 
if has_unsaved:
    st.warning(
        "⚠️ You have entries that are **not yet saved to the server**. "
        "Click **Save entries to server** below before leaving this page.",
        icon="⚠️",
    )
else:
    st.caption("✅ All entries are saved to the server.")
 
col_save, col_clear, col_reload = st.columns([2, 1, 1])
 
with col_save:
    if st.button(
        "💾 Save entries to server",
        type="primary",
        use_container_width=True,
        help=(
            "Writes all entries to the shared data file on the server "
            "(the same file the dashboard reads). Do this before you leave "
            "the page — unsaved entries are lost on refresh."
        ),
    ):
        try:
            n_new = write_field_csv(st.session_state.rows, OUTPUT_PATH)
            # Re-sync memory with disk so the unsaved indicator clears and
            # future saves compute their delta correctly.
            st.session_state.rows = load_existing_rows(OUTPUT_PATH)
            st.session_state.saved_row_count = len(st.session_state.rows)
            if n_new > 0:
                st.success(
                    f"✅ Saved. {n_new} new row(s) written to the server. "
                    f"{len(st.session_state.rows)} rows total on file."
                )
            else:
                st.success(
                    "✅ Already up to date — everything in memory was already "
                    "saved. No new rows to write."
                )
            st.rerun()
        except Exception as e:
            st.error(
                f"❌ SAVE FAILED — your entries are NOT on the server. "
                f"Do not leave the page. Error: {e}"
            )
 
with col_clear:
    if st.button(
        "Clear entry list",
        use_container_width=True,
        help=(
            "Empties the review list on THIS page only. Does not delete "
            "anything already saved to the server. Use this to start a "
            "fresh list after you've saved."
        ),
    ):
        st.session_state["_confirm_clear"] = True
 
with col_reload:
    if st.button(
        "Load saved data",
        use_container_width=True,
        help=(
            "Discards the current review list and reloads the saved file "
            "from the server. Any unsaved entries on this page are lost."
        ),
    ):
        st.session_state.rows = load_existing_rows(OUTPUT_PATH)
        st.session_state.saved_row_count = len(st.session_state.rows)
        st.rerun()
 
# Confirm step for Clear so a stray click can't wipe an unsaved list.
if st.session_state.get("_confirm_clear"):
    st.markdown("---")
    if has_unsaved:
        st.error(
            "You have **unsaved entries**. Clearing the list now will lose "
            "them. Save first if you need them."
        )
    else:
        st.info("This empties the on-page list. Saved data on the server is untouched.")
    c1, c2 = st.columns(2)
    with c1:
        if st.button("Yes, clear the list", type="primary", use_container_width=True):
            st.session_state.rows = pd.DataFrame(columns=COLUMNS)
            st.session_state.saved_row_count = 0
            st.session_state["_confirm_clear"] = False
            st.rerun()
    with c2:
        if st.button("Cancel", use_container_width=True):
            st.session_state["_confirm_clear"] = False
            st.rerun()
 